namespace Farm.Web.Api.Services.Calibration.Generation;

/// <summary>
/// The complete allowlist of Klipper-dialect commands the trusted generator may emit and the static
/// validator will accept.
/// </summary>
/// <remarks>
/// The list is intentionally minimal. It contains no shell, host, file, network, macro-definition or
/// firmware tuning command. In particular <c>TUNING_TOWER</c> is never emitted and is rejected on
/// sight, because a firmware-driven tower would move the tuned parameter outside the server's static
/// safety envelope.
/// </remarks>
public static class KlipperCalibrationCommands
{
    /// <summary>The forbidden firmware tuning tower macro.</summary>
    public const string TuningTower = "TUNING_TOWER";

    /// <summary>Every command the trusted generator may emit.</summary>
    public static IReadOnlySet<string> Allowlist { get; } = new HashSet<string>(StringComparer.Ordinal)
    {
        "G0",
        "G1",
        "G4",
        "G21",
        "G28",
        "G90",
        "G91",
        "G92",
        "M82",
        "M83",
        "M84",
        "M104",
        "M106",
        "M107",
        "M109",
        "M140",
        "M141",
        "M190",
        "M191",
        "M204",
        "M220",
        "M221",
        "SET_PRESSURE_ADVANCE",
        "SET_VELOCITY_LIMIT",
        "TURN_OFF_HEATERS",
    };

    /// <summary>Commands that are explicitly forbidden even if a future allowlist grows.</summary>
    public static IReadOnlySet<string> Forbidden { get; } = new HashSet<string>(StringComparer.Ordinal)
    {
        TuningTower,
        "RUN_SHELL_COMMAND",
        "SAVE_CONFIG",
        "RESTART",
        "FIRMWARE_RESTART",
        "M112",
        "M117",
        "M118",
        "M28",
        "M29",
        "M30",
        "M32",
        "M33",
        "M928",
    };

    /// <summary>Determines whether a command token is on the trusted allowlist.</summary>
    /// <param name="command">The uppercase command token.</param>
    /// <returns><see langword="true"/> when the command may appear in calibration G-code.</returns>
    public static bool IsAllowed(string command) =>
        !string.IsNullOrEmpty(command) &&
        !Forbidden.Contains(command) &&
        Allowlist.Contains(command);
}

/// <summary>The stable machine-readable marker vocabulary shared by the generator and annotator.</summary>
public static class CalibrationGcodeMarkers
{
    /// <summary>Marks the start of the trusted generated program body.</summary>
    public const string ProgramBegin = ";PF_BEGIN";

    /// <summary>Marks the end of the trusted generated program body.</summary>
    public const string ProgramEnd = ";PF_END";

    /// <summary>Marks the initialization block.</summary>
    public const string Initialize = ";PF_INIT";

    /// <summary>Marks the finalization block.</summary>
    public const string Finalize = ";PF_FINALIZE";

    /// <summary>Marks the start of a calibration segment.</summary>
    public const string SegmentBegin = ";PF_SEG_BEGIN";

    /// <summary>Marks the end of a calibration segment.</summary>
    public const string SegmentEnd = ";PF_SEG_END";

    /// <summary>Marks a safe transition between segments.</summary>
    public const string SegmentTransition = ";PF_SEG_TRANSITION";

    /// <summary>Prefix of every provenance header line the annotator writes.</summary>
    public const string HeaderPrefix = ";PF_META";
}

/// <summary>Where the printable body of a program comes from.</summary>
public enum CalibrationGcodeBodySource
{
    /// <summary>Unknown. Never a valid value.</summary>
    Unspecified = 0,

    /// <summary>Every printed move was generated by this trusted server generator.</summary>
    ServerGenerated = 1,

    /// <summary>
    /// The envelope was generated by this server and the printable body is produced by the pinned
    /// upstream slicer from the linked, validated asset.
    /// </summary>
    SlicedFromLinkedAsset = 2,
}

/// <summary>A trusted, deterministic Klipper program produced for one calibration attempt.</summary>
/// <param name="Text">The program text, using <c>\n</c> line endings only.</param>
/// <param name="BodySource">Where the printable body comes from.</param>
/// <param name="SegmentCount">Number of emitted segments.</param>
/// <param name="Sha256">The digest of <paramref name="Text"/>.</param>
public sealed record KlipperCalibrationProgram(
    string Text,
    CalibrationGcodeBodySource BodySource,
    int SegmentCount,
    string Sha256);

/// <summary>
/// Generates the trusted Klipper command dialect required by the supported calibration methods.
/// </summary>
public interface IKlipperCalibrationGcodeGenerator
{
    /// <summary>
    /// Generates a deterministic Klipper program for a compiled specification and plan.
    /// </summary>
    /// <param name="specification">The compiled specification.</param>
    /// <param name="plan">The compiled upstream-Orca plan.</param>
    /// <returns>The generated program, or the ordered rejection reasons.</returns>
    /// <remarks>
    /// All output uses <see cref="System.Globalization.CultureInfo.InvariantCulture"/>, fixed decimal
    /// precision, stable command ordering and <c>\n</c> newlines, so identical inputs always produce
    /// byte-identical output. Pressure advance line and pattern geometry is computed here from bounded
    /// server-side arithmetic; no renderer is invoked and no caller-supplied G-code is ever accepted.
    /// </remarks>
    CalibrationGenerationResult<KlipperCalibrationProgram> Generate(
        CalibrationSpecification specification,
        OrcaCalibrationPlan plan);
}
