using System.Text;
using Farm.Web.Shared;

namespace Farm.Web.Api.Services.SlicerServices;

internal static class SlicerArgTemplateBuilder
{
    public static string GenerateOrcaSlicerConfig(SlicerProfileDto? profile)
    {
        StringBuilder cfg = new();
        double layerHeight = profile?.ProcessProfile?.LayerHeight ?? 0.2;
        int infill = profile?.ProcessProfile?.InfillPercentage ?? 20;
        int printSpeed = profile?.ProcessProfile?.PrintSpeed ?? profile?.FilamentProfile?.PrintSpeed ?? 50;
        int nozzleTemp = profile?.FilamentProfile?.NozzleTemperature ?? 210;
        int bedTemp = profile?.FilamentProfile?.BedTemperature ?? 60;
        string material = profile?.FilamentProfile?.Material ?? "PLA";
        bool supports = profile?.ProcessProfile?.Supports ?? false;

        _ = cfg.AppendLine("# Generated by PrintFarmer OrcaSlicer integration");
        _ = cfg.AppendLine($"# Generated at {DateTime.UtcNow:O}");
        _ = cfg.AppendLine();
        _ = cfg.AppendLine("[print]");
        _ = cfg.AppendLine($"layer_height = {layerHeight}");
        _ = cfg.AppendLine($"first_layer_height = {layerHeight * 1.5}");
        _ = cfg.AppendLine("perimeters = 2");
        _ = cfg.AppendLine("top_solid_layers = 3");
        _ = cfg.AppendLine("bottom_solid_layers = 3");
        _ = cfg.AppendLine($"fill_density = {infill / 100.0:F2}");
        _ = cfg.AppendLine("fill_pattern = cubic");
        _ = cfg.AppendLine();
        _ = cfg.AppendLine("[speeds]");
        _ = cfg.AppendLine($"perimeter_speed = {printSpeed}");
        _ = cfg.AppendLine($"infill_speed = {printSpeed * 1.2:F0}");
        _ = cfg.AppendLine("travel_speed = 120");
        _ = cfg.AppendLine($"first_layer_speed = {printSpeed * 0.5:F0}");
        _ = cfg.AppendLine();
        _ = cfg.AppendLine("[filament]");
        _ = cfg.AppendLine($"temperature = {nozzleTemp}");
        _ = cfg.AppendLine($"first_layer_temperature = {nozzleTemp + 5}");
        _ = cfg.AppendLine($"bed_temperature = {bedTemp}");
        _ = cfg.AppendLine($"filament_type = {material}");
        _ = cfg.AppendLine();
        if (supports)
        {
            _ = cfg.AppendLine("[support]");
            _ = cfg.AppendLine("support_material = 1");
            _ = cfg.AppendLine("support_material_auto = 1");
            _ = cfg.AppendLine("support_material_threshold = 45");
            _ = cfg.AppendLine("support_material_pattern = rectilinear");
            _ = cfg.AppendLine("support_material_spacing = 2.5");
            _ = cfg.AppendLine("support_material_interface_layers = 2");
            _ = cfg.AppendLine();
        }

        _ = cfg.AppendLine("[printer]");
        _ = cfg.AppendLine("nozzle_diameter = 0.4");
        _ = cfg.AppendLine("extruder_count = 1");
        _ = cfg.AppendLine();
        return cfg.ToString();
    }

    public static string GeneratePrusaSlicerConfig(SlicerProfileDto? profile)
    {
        StringBuilder cfg = new();
        double layerHeight = profile?.ProcessProfile?.LayerHeight ?? 0.2;
        int infill = profile?.ProcessProfile?.InfillPercentage ?? 20;
        int nozzleTemp = profile?.FilamentProfile?.NozzleTemperature ?? 210;
        int bedTemp = profile?.FilamentProfile?.BedTemperature ?? 60;

        _ = cfg.AppendLine("# Generated by PrintFarmer PrusaSlicer integration");
        _ = cfg.AppendLine($"# Generated at {DateTime.UtcNow:O}");
        _ = cfg.AppendLine();
        _ = cfg.AppendLine("[general]");
        _ = cfg.AppendLine($"layer_height = {layerHeight}");
        _ = cfg.AppendLine($"perimeters = 2");
        _ = cfg.AppendLine($"infill = {infill}");
        _ = cfg.AppendLine();
        _ = cfg.AppendLine("[printer]");
        _ = cfg.AppendLine("nozzle_diameter = 0.4");
        _ = cfg.AppendLine("extruder_count = 1");
        _ = cfg.AppendLine();
        _ = cfg.AppendLine("[filament]");
        _ = cfg.AppendLine($"temperature = {nozzleTemp}");
        _ = cfg.AppendLine($"bed_temperature = {bedTemp}");
        return cfg.ToString();
    }

    public const string DefaultOrcaArgsTemplate = "--config \"{config}\" --output \"{output}\" {input}";
}
