using System.Text;
using Farm.Web.Shared;

namespace Farm.Web.Api.Services.SlicerServices;

internal static class SlicerArgTemplateBuilder
{
    public static string GenerateOrcaSlicerConfig(SlicerProfileDto? profile)
    {
        var cfg = new StringBuilder();
        cfg.AppendLine("# Generated by PrintFarmer OrcaSlicer integration");
        cfg.AppendLine($"# Generated at {DateTime.UtcNow:O}");
        cfg.AppendLine();
        cfg.AppendLine("[print]");
        cfg.AppendLine($"layer_height = {profile?.LayerHeight ?? 0.2}");
        cfg.AppendLine($"first_layer_height = {(profile?.LayerHeight ?? 0.2) * 1.5}");
        cfg.AppendLine("perimeters = 2");
        cfg.AppendLine("top_solid_layers = 3");
        cfg.AppendLine("bottom_solid_layers = 3");
        cfg.AppendLine($"fill_density = {(profile?.InfillPercentage ?? 20) / 100.0:F2}");
        cfg.AppendLine("fill_pattern = cubic");
        cfg.AppendLine();
        cfg.AppendLine("[speeds]");
        cfg.AppendLine($"perimeter_speed = {profile?.PrintSpeed ?? 50}");
        cfg.AppendLine($"infill_speed = {(profile?.PrintSpeed ?? 50) * 1.2:F0}");
        cfg.AppendLine("travel_speed = 120");
        cfg.AppendLine($"first_layer_speed = {(profile?.PrintSpeed ?? 50) * 0.5:F0}");
        cfg.AppendLine();
        cfg.AppendLine("[filament]");
        cfg.AppendLine($"temperature = {profile?.NozzleTemperature ?? 210}");
        cfg.AppendLine($"first_layer_temperature = {(profile?.NozzleTemperature ?? 210) + 5}");
        cfg.AppendLine($"bed_temperature = {profile?.BedTemperature ?? 60}");
        cfg.AppendLine($"filament_type = {profile?.Material ?? "PLA"}");
        cfg.AppendLine();
        if (profile?.Supports == true)
        {
            cfg.AppendLine("[support]");
            cfg.AppendLine("support_material = 1");
            cfg.AppendLine("support_material_auto = 1");
            cfg.AppendLine("support_material_threshold = 45");
            cfg.AppendLine("support_material_pattern = rectilinear");
            cfg.AppendLine("support_material_spacing = 2.5");
            cfg.AppendLine("support_material_interface_layers = 2");
            cfg.AppendLine();
        }

        cfg.AppendLine("[printer]");
        cfg.AppendLine("nozzle_diameter = 0.4");
        cfg.AppendLine("extruder_count = 1");
        cfg.AppendLine();
        return cfg.ToString();
    }

    public static string GeneratePrusaSlicerConfig(Farm.Web.Shared.SlicerProfileDto? profile)
    {
        var cfg = new System.Text.StringBuilder();
        cfg.AppendLine("# Generated by PrintFarmer PrusaSlicer integration");
        cfg.AppendLine($"# Generated at {DateTime.UtcNow:O}");
        cfg.AppendLine();
        cfg.AppendLine("[general]");
        cfg.AppendLine($"layer_height = {profile?.LayerHeight ?? 0.2}");
        cfg.AppendLine($"perimeters = 2");
        cfg.AppendLine($"infill = {(profile?.InfillPercentage ?? 20)}");
        cfg.AppendLine();
        cfg.AppendLine("[printer]");
        cfg.AppendLine("nozzle_diameter = 0.4");
        cfg.AppendLine("extruder_count = 1");
        cfg.AppendLine();
        cfg.AppendLine("[filament]");
        cfg.AppendLine($"temperature = {profile?.NozzleTemperature ?? 210}");
        cfg.AppendLine($"bed_temperature = {profile?.BedTemperature ?? 60}");
        return cfg.ToString();
    }

    public const string DefaultOrcaArgsTemplate = "--config \"{config}\" --output \"{output}\" {input}";
}
