namespace Farm.Slicer.Module.Services;

/// <summary>
/// Raised when a registration matches an existing <c>SlicerService</c>/<c>Worker</c> row by
/// <c>InstanceId</c>, but the incumbent worker is not <see cref="Farm.Slicer.Module.Domain.WorkerStatus.Offline"/>.
/// </summary>
/// <remarks>
/// Worker registration is gated only by a shared registration key, not a per-worker secret. Without
/// this guard, anyone holding that shared key could register using a healthy, currently-heartbeating
/// worker's <c>InstanceId</c> to silently overwrite its credentials and revoke it from the pool — a
/// denial-of-service against a running worker (issue #1860). <c>InstanceId</c> values generated by
/// <c>scripts/docker/compose-generator.sh</c> are predictable (<c>orcaslicer-worker-N</c>), which
/// makes this guessable rather than merely theoretical.
///
/// The incumbent's <see cref="Farm.Slicer.Module.Domain.Worker.Status"/> only becomes
/// <see cref="Farm.Slicer.Module.Domain.WorkerStatus.Offline"/> via an authenticated deregistration
/// (the worker itself, using its own credentials) or the background heartbeat monitor detecting a
/// stale heartbeat past its timeout. Rejecting a claim while the incumbent is anything else preserves
/// legitimate crash recovery — the replacement can reclaim the identity once the incumbent is
/// reclassified Offline — while closing the window on squatting a live identity.
/// </remarks>
public sealed class SlicerInstanceIdConflictException : Exception
{
    /// <summary>Stable machine-readable reason code for this conflict.</summary>
    public const string Code = "instance_id_worker_online";

    /// <summary>Initializes a new instance with a default message and no known <c>InstanceId</c>.</summary>
    public SlicerInstanceIdConflictException()
        : base("Registration was rejected: the existing worker is not Offline.")
    {
    }

    /// <summary>Initializes a new instance with a message and no known <c>InstanceId</c>.</summary>
    /// <param name="message">Non-sensitive description of the failure.</param>
    public SlicerInstanceIdConflictException(string message)
        : base(message)
    {
    }

    /// <summary>Initializes a new instance with a message and inner exception.</summary>
    /// <param name="message">Non-sensitive description of the failure.</param>
    /// <param name="innerException">The underlying failure.</param>
    public SlicerInstanceIdConflictException(string message, Exception innerException)
        : base(message, innerException)
    {
    }

    /// <summary>The <c>InstanceId</c> presented by the rejected registration.</summary>
    public string InstanceId { get; init; } = string.Empty;

    /// <summary>Creates an instance carrying the conflicting <c>InstanceId</c>, for use by production callers.</summary>
    /// <param name="instanceId">The <c>InstanceId</c> whose incumbent worker is not Offline.</param>
    public static SlicerInstanceIdConflictException ForInstanceId(string instanceId) =>
        new($"Registration for InstanceId '{instanceId}' was rejected: the existing worker is not Offline.")
        {
            InstanceId = instanceId,
        };
}
