using Farm.Moonraker.Emulator.Options;
using Microsoft.Extensions.Options;

namespace Farm.Moonraker.Emulator.Domain;

/// <summary>
/// Owns the single <see cref="PrinterAggregate"/> this emulator process instance
/// serves. Configured entirely from <see cref="EmulatorOptions"/>
/// (Scenario/PrinterId/PrinterName) — every request is answered by this one printer at
/// Moonraker's normal root paths. Multi-printer topologies come from running multiple
/// isolated process/container instances (e.g. separate Compose services), never from
/// dispatching within a single process by Host header or path prefix.
/// </summary>
public sealed class PrinterRegistry
{
    public PrinterAggregate Printer { get; }

    public FaultRuleEngine Rules { get; } = new();

    public PrinterRegistry(IOptions<EmulatorOptions> options)
    {
        EmulatorOptions settings = options.Value;
        PrinterScenario scenario = Enum.TryParse(settings.Scenario, ignoreCase: true, out PrinterScenario parsed)
            ? parsed
            : throw new InvalidOperationException(
                $"Unknown Emulator:Scenario '{settings.Scenario}'. Expected Ready, Printing, Paused, or Shutdown.");

        Printer = new PrinterAggregate
        {
            Id = settings.PrinterId,
            Name = settings.PrinterName,
            InitialScenario = scenario,
        };
        Printer.ResetToScenario(scenario);
        SeedFixtures(Printer);
    }

    private static void SeedFixtures(PrinterAggregate printer)
    {
        byte[] gcode = System.Text.Encoding.UTF8.GetBytes(
            "; generated by the PrintFarmer Moonraker emulator\n" +
            "; slicer = OrcaSlicer\n" +
            "G28\nG1 X10 Y10 Z0.2 F3000\n");
        VirtualGcodeMetadata metadata = new();
        metadata.Thumbnails.Add(new VirtualThumbnail(32, 32, 900, "thumbs/benchy-32x32.png"));
        metadata.Thumbnails.Add(new VirtualThumbnail(300, 300, 21000, "thumbs/benchy-300x300.png"));
        metadata.Objects.Add(new VirtualPrintObject("benchy_hull", [50, 50]));
        metadata.Objects.Add(new VirtualPrintObject("benchy_cabin", [60, 60]));
        printer.Files.Seed("gcodes", "benchy.gcode", gcode, metadata);

        // Qidibox's real dictionary fetch (MoonrakerSubscriptionService.FetchQidiboxDictionaryAsync)
        // reads this exact path via a raw HttpClient GET, independent of MMU mode — seeding it
        // unconditionally costs nothing and means it's already present whichever mode a test
        // switches to later.
        printer.Files.Seed("config", "officiall_filas_list.cfg", System.Text.Encoding.UTF8.GetBytes(MmuFixture.QidiboxDictionaryIniContent));

        // Explicit, stable uid — see the fidelity note on WebcamFixture.Uid — so this
        // seeded webcam's identifier is reproducible across process restarts instead of
        // a fresh random GUID each time.
        printer.Webcams.Add(new WebcamFixture { Name = "Nozzle Cam", Uid = "nozzle-cam" });

        printer.History.Add(new HistoryJobEntry
        {
            JobId = "seed0001",
            Filename = "calibration_cube.gcode",
            StartTime = 1704067200,
            EndTime = 1704070800,
            PrintDuration = 3550,
            TotalDuration = 3600,
            FilamentUsed = 12.4,
            Status = "completed",
        });
    }
}
