using System.Text.Json.Serialization;

namespace Farm.Web.Api.Controllers.Requests;

/// <summary>Bounded relative extrusion request generated by maintenance controls.</summary>
public sealed class ExtrudeFilamentRequest
{
    [JsonPropertyName("distanceMm")]
    public double DistanceMm { get; set; }

    [JsonPropertyName("feedrateMmPerMinute")]
    public int FeedrateMmPerMinute { get; set; }
}

/// <summary>Typed protocol-specific MMU gate action.</summary>
public sealed class MmuGateActionRequest
{
    [JsonPropertyName("protocol")]
    public string Protocol { get; set; } = string.Empty;

    [JsonPropertyName("action")]
    public string Action { get; set; } = string.Empty;

    [JsonPropertyName("gateIndex")]
    public int? GateIndex { get; set; }

    [JsonPropertyName("laneName")]
    public string? LaneName { get; set; }
}
