// Tests for per-extruder filament parsing (Phase 2). Properties added by Phase 1 domain changes.
// These tests reference FilamentPerExtruderWeightG, FilamentPerExtruderLengthMm, and ExtruderCount
// which will be added to GcodeMetadataExtracted by Lambert in Phase 1.

using Farm.Infrastructure.Services.Gcode;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;

namespace Farm.Web.Api.Tests.Infrastructure;

public class GcodeMetadataPerExtruderFilamentTests
{
    private readonly GcodeMetadataExtractorService _service;

    public GcodeMetadataPerExtruderFilamentTests()
    {
        Mock<ILogger<GcodeMetadataExtractorService>> loggerMock = new();
        _service = new GcodeMetadataExtractorService(loggerMock.Object);
    }

    // -------------------------------------------------------
    // Single extruder — backward compatibility
    // -------------------------------------------------------

    [Fact]
    public async Task ExtractMetadataAsync_SingleExtruderWeightG_ReturnsOneElementArray()
    {
        string gcodeContent = """
            ; generated by PrusaSlicer 2.8.0
            ; filament used [g] = 10.30
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderWeightG.Should().NotBeNull();
        result.FilamentPerExtruderWeightG.Should().HaveCount(1);
        result.FilamentPerExtruderWeightG![0].Should().BeApproximately(10.30, 0.001);
        result.FilamentWeightGrams.Should().BeApproximately(10.30, 0.001);
    }

    [Fact]
    public async Task ExtractMetadataAsync_SingleExtruderLengthMm_ReturnsOneElementArray()
    {
        string gcodeContent = """
            ; generated by PrusaSlicer 2.8.0
            ; filament used [mm] = 3432.2
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderLengthMm.Should().NotBeNull();
        result.FilamentPerExtruderLengthMm.Should().HaveCount(1);
        result.FilamentPerExtruderLengthMm![0].Should().BeApproximately(3432.2, 0.01);
        result.FilamentLengthMm.Should().BeApproximately(3432.2, 0.01);
    }

    // -------------------------------------------------------
    // Two extruders — common MMU / dual-extruder setups
    // -------------------------------------------------------

    [Fact]
    public async Task ExtractMetadataAsync_TwoExtruderWeightG_ParsesBothValues()
    {
        string gcodeContent = """
            ; generated by OrcaSlicer 2.3.1
            ; filament used [g] = 10.30,3.80
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderWeightG.Should().NotBeNull();
        result.FilamentPerExtruderWeightG.Should().HaveCount(2);
        result.FilamentPerExtruderWeightG![0].Should().BeApproximately(10.30, 0.001);
        result.FilamentPerExtruderWeightG![1].Should().BeApproximately(3.80, 0.001);
        result.FilamentWeightGrams.Should().BeApproximately(14.10, 0.001);
    }

    [Fact]
    public async Task ExtractMetadataAsync_TwoExtruderLengthMm_ParsesBothValues()
    {
        string gcodeContent = """
            ; generated by OrcaSlicer 2.3.1
            ; filament used [mm] = 3432.2,1208.1
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderLengthMm.Should().NotBeNull();
        result.FilamentPerExtruderLengthMm.Should().HaveCount(2);
        result.FilamentPerExtruderLengthMm![0].Should().BeApproximately(3432.2, 0.01);
        result.FilamentPerExtruderLengthMm![1].Should().BeApproximately(1208.1, 0.01);
        result.FilamentLengthMm.Should().BeApproximately(4640.3, 0.01);
    }

    [Fact]
    public async Task ExtractMetadataAsync_TwoExtruders_ExtruderCountIsTwo()
    {
        string gcodeContent = """
            ; generated by PrusaSlicer 2.8.0
            ; filament used [g] = 10.30,3.80
            ; filament used [mm] = 3432.2,1208.1
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.ExtruderCount.Should().Be(2);
    }

    // -------------------------------------------------------
    // Four extruders — Snapmaker U1, Prusa XL, Bambu AMS
    // -------------------------------------------------------

    [Fact]
    public async Task ExtractMetadataAsync_FourExtruderWeightG_ParsesAllValues()
    {
        string gcodeContent = """
            ; generated by OrcaSlicer 2.3.1
            ; filament used [g] = 5.20,3.10,7.40,2.80
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderWeightG.Should().NotBeNull();
        result.FilamentPerExtruderWeightG.Should().HaveCount(4);
        result.FilamentPerExtruderWeightG![0].Should().BeApproximately(5.20, 0.001);
        result.FilamentPerExtruderWeightG![1].Should().BeApproximately(3.10, 0.001);
        result.FilamentPerExtruderWeightG![2].Should().BeApproximately(7.40, 0.001);
        result.FilamentPerExtruderWeightG![3].Should().BeApproximately(2.80, 0.001);
        result.FilamentWeightGrams.Should().BeApproximately(18.50, 0.001);
    }

    [Fact]
    public async Task ExtractMetadataAsync_FourExtruders_ExtruderCountIsFour()
    {
        string gcodeContent = """
            ; generated by OrcaSlicer 2.3.1
            ; filament used [g] = 5.20,3.10,7.40,2.80
            ; filament used [mm] = 1740.0,1040.0,2480.0,940.0
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.ExtruderCount.Should().Be(4);
    }

    // -------------------------------------------------------
    // Single extruder — ExtruderCount
    // -------------------------------------------------------

    [Fact]
    public async Task ExtractMetadataAsync_SingleExtruder_ExtruderCountIsOneOrNull()
    {
        string gcodeContent = """
            ; generated by PrusaSlicer 2.8.0
            ; filament used [g] = 10.30
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        // Single extruder: ExtruderCount should be 1 (or null to match existing behavior)
        result.ExtruderCount.Should().Match(v => v == null || v == 1);
    }

    // -------------------------------------------------------
    // Edge cases
    // -------------------------------------------------------

    [Fact]
    public async Task ExtractMetadataAsync_SpacesAfterCommas_ParsesCorrectly()
    {
        string gcodeContent = """
            ; generated by PrusaSlicer 2.8.0
            ; filament used [g] = 10.30, 3.80
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderWeightG.Should().NotBeNull();
        result.FilamentPerExtruderWeightG.Should().HaveCount(2);
        result.FilamentPerExtruderWeightG![0].Should().BeApproximately(10.30, 0.001);
        result.FilamentPerExtruderWeightG![1].Should().BeApproximately(3.80, 0.001);
    }

    [Fact]
    public async Task ExtractMetadataAsync_TrailingComma_HandlesGracefully()
    {
        string gcodeContent = """
            ; generated by OrcaSlicer 2.3.1
            ; filament used [g] = 10.30,3.80,
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        // Should parse the two valid values and ignore trailing comma
        result.FilamentPerExtruderWeightG.Should().NotBeNull();
        result.FilamentPerExtruderWeightG.Should().HaveCount(2);
        result.FilamentPerExtruderWeightG![0].Should().BeApproximately(10.30, 0.001);
        result.FilamentPerExtruderWeightG![1].Should().BeApproximately(3.80, 0.001);
    }

    [Fact]
    public async Task ExtractMetadataAsync_ZeroUsageOnSomeExtruders_IncludesZerosInArray()
    {
        string gcodeContent = """
            ; generated by OrcaSlicer 2.3.1
            ; filament used [g] = 10.30,0.00,7.40,0.00
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderWeightG.Should().NotBeNull();
        result.FilamentPerExtruderWeightG.Should().HaveCount(4);
        result.FilamentPerExtruderWeightG![0].Should().BeApproximately(10.30, 0.001);
        result.FilamentPerExtruderWeightG![1].Should().BeApproximately(0.00, 0.001);
        result.FilamentPerExtruderWeightG![2].Should().BeApproximately(7.40, 0.001);
        result.FilamentPerExtruderWeightG![3].Should().BeApproximately(0.00, 0.001);
        result.FilamentWeightGrams.Should().BeApproximately(17.70, 0.001);
        result.ExtruderCount.Should().Be(4);
    }

    [Fact]
    public async Task ExtractMetadataAsync_MultiExtruderDoesNotBreakExistingSingleValueParsing()
    {
        // Ensure that even with per-extruder data, the existing single-value
        // FilamentWeightGrams and FilamentLengthMm remain populated as totals
        string gcodeContent = """
            ; generated by OrcaSlicer 2.3.1
            ; filament_type = PLA;PETG
            ; filament used [g] = 10.30,3.80
            ; filament used [mm] = 3432.2,1208.1
            ; nozzle_diameter = 0.4
            ; layer_height = 0.2
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        // Existing single-value fields remain populated with totals
        result.FilamentWeightGrams.Should().NotBeNull();
        result.FilamentWeightGrams.Should().BeApproximately(14.10, 0.001);
        result.FilamentLengthMm.Should().NotBeNull();
        result.FilamentLengthMm.Should().BeApproximately(4640.3, 0.01);

        // Other metadata is unaffected
        result.NozzleDiameter.Should().Be(0.4);
        result.LayerHeight.Should().Be(0.2);
    }

    // -------------------------------------------------------
    // Combined weight + length multi-extruder
    // -------------------------------------------------------

    [Fact]
    public async Task ExtractMetadataAsync_BothWeightAndLengthMultiExtruder_ParsesBothArrays()
    {
        string gcodeContent = """
            ; generated by PrusaSlicer 2.8.0
            ; filament used [g] = 10.30,3.80
            ; filament used [mm] = 3432.2,1208.1
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderWeightG.Should().HaveCount(2);
        result.FilamentPerExtruderLengthMm.Should().HaveCount(2);
        result.FilamentWeightGrams.Should().BeApproximately(14.10, 0.001);
        result.FilamentLengthMm.Should().BeApproximately(4640.3, 0.01);
    }

    [Fact]
    public async Task ExtractMetadataAsync_FourExtruderLengthMm_ParsesAllValues()
    {
        string gcodeContent = """
            ; generated by OrcaSlicer 2.3.1
            ; filament used [mm] = 1740.0,1040.0,2480.0,940.0
            G28
            """;

        GcodeMetadataExtracted result = await _service.ExtractMetadataAsync(gcodeContent);

        result.FilamentPerExtruderLengthMm.Should().NotBeNull();
        result.FilamentPerExtruderLengthMm.Should().HaveCount(4);
        result.FilamentPerExtruderLengthMm![0].Should().BeApproximately(1740.0, 0.01);
        result.FilamentPerExtruderLengthMm![1].Should().BeApproximately(1040.0, 0.01);
        result.FilamentPerExtruderLengthMm![2].Should().BeApproximately(2480.0, 0.01);
        result.FilamentPerExtruderLengthMm![3].Should().BeApproximately(940.0, 0.01);
        result.FilamentLengthMm.Should().BeApproximately(6200.0, 0.01);
    }
}
