using Farm.Infrastructure.Services.Gcode;
using Farm.Infrastructure.Telemetry;
using FluentAssertions;
using Moq;

namespace Farm.Web.Api.Tests.Infrastructure;

public class GcodeMetadataExtractorServiceTests
{
    private readonly Mock<IUnifiedLoggingService> _loggerMock;
    private readonly GcodeMetadataExtractorService _service;

    public GcodeMetadataExtractorServiceTests()
    {
        _loggerMock = new Mock<IUnifiedLoggingService>();
        _service = new GcodeMetadataExtractorService(_loggerMock.Object);
    }

    [Fact]
    public async Task ExtractMetadataAsync_EmptyContent_ReturnsEmptyMetadata()
    {
        var result = await _service.ExtractMetadataAsync("");

        result.Should().NotBeNull();
        result.SlicerName.Should().BeNull();
        result.Material.Should().BeNull();
    }

    [Fact]
    public async Task ExtractMetadataAsync_NullContent_ReturnsEmptyMetadata()
    {
        var result = await _service.ExtractMetadataAsync(null!);

        result.Should().NotBeNull();
        result.SlicerName.Should().BeNull();
    }

    [Fact]
    public async Task ExtractMetadataAsync_PrusaSlicerContent_ExtractsSlicerInfo()
    {
        string gcodeContent = @"; generated by PrusaSlicer 2.5.0 on 2024-01-15
; filament_type = PLA
; layer_height = 0.2
M109 S210
G28
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        result.SlicerName.Should().Contain("PrusaSlicer");
        result.SlicerVersion.Should().Be("2.5.0");
        result.Material.Should().Be("PLA");
        result.LayerHeight.Should().Be(0.2);
    }

    [Fact]
    public async Task ExtractMetadataAsync_OrcaSlicerContent_ExtractsSlicerInfo()
    {
        string gcodeContent = @"; generated by OrcaSlicer 1.7.0 on 2024-01-15
; filament_type = PETG
; nozzle_diameter = 0.4
M109 S220
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        result.SlicerName.Should().Contain("OrcaSlicer");
        result.SlicerVersion.Should().Be("1.7.0");
        result.Material.Should().Be("PETG");
        result.NozzleDiameter.Should().Be(0.4);
    }

    [Fact]
    public async Task ExtractMetadataAsync_CuraContent_ExtractsSlicerInfo()
    {
        string gcodeContent = @"; Cura_Version:5.0.0
; MATERIAL = ABS
; LAYER_HEIGHT = 0.15
G28
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        result.SlicerName.Should().Be("Cura");
        result.SlicerVersion.Should().Be("5.0.0");
        result.Material.Should().Be("ABS");
        result.LayerHeight.Should().Be(0.15);
    }

    [Fact]
    public async Task ExtractMetadataAsync_ExtractsPrintTime()
    {
        string gcodeContent = @"; estimated printing time (normal mode) = 2h 30m 45s
; filament_g = 25.5
M109 S200
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        result.EstimatedPrintTimeMinutes.Should().BeApproximately(150.75, 0.01);
        result.FilamentWeightGrams.Should().Be(25.5);
    }

    [Fact]
    public async Task ExtractMetadataAsync_ExtractsFilamentInfo()
    {
        string gcodeContent = @"; filament_g = 42.5
; filament_length = 5000
M104 S200
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        result.FilamentWeightGrams.Should().Be(42.5);
        result.FilamentLengthMm.Should().Be(5000);
    }

    [Fact]
    public async Task ExtractMetadataAsync_HandlesLongGcodeFile()
    {
        // Create a long G-code with metadata in first 500 lines
        var lines = new List<string> { "; generated by PrusaSlicer 2.5.0" };
        lines.AddRange(Enumerable.Range(0, 600).Select(i => $"G1 X{i} Y{i} Z0.2"));

        string gcodeContent = string.Join("\n", lines);

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        result.SlicerName.Should().Contain("PrusaSlicer");
    }

    [Fact]
    public async Task ExtractMetadataAsync_HandlesMissingMetadata()
    {
        string gcodeContent = @"G28
G29
M104 S200
M109 S200
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        result.SlicerName.Should().BeNull();
        result.Material.Should().BeNull();
    }

    [Fact]
    public async Task ExtractMetadataAsync_ExtractsMultipleMetadataFields()
    {
        string gcodeContent = @"; generated by PrusaSlicer 2.5.0
; filament_type = PLA
; nozzle_diameter = 0.4
; layer_height = 0.2
; filament_g = 42.5
M104 S200
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        result.SlicerName.Should().Contain("PrusaSlicer");
        result.Material.Should().Be("PLA");
        result.NozzleDiameter.Should().Be(0.4);
        result.LayerHeight.Should().Be(0.2);
        result.FilamentWeightGrams.Should().Be(42.5);
    }

    [Fact]
    public async Task ExtractMetadataAsync_HandlesVariationInCommentFormat()
    {
        string gcodeContent = @"; Generated by PrusaSlicer 2.5.0
;filament_type = PETG
; LAYER_HEIGHT = 0.25
; Nozzle_Diameter = 0.6
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        // Should handle case-insensitive matching
        result.SlicerName.Should().Contain("PrusaSlicer");
    }

    [Fact]
    public async Task ExtractMetadataAsync_HandlesExceptionGracefully()
    {
        // Test with content that might cause parsing issues
        string gcodeContent = @"; some comment with special chars: !@#$%^&*()
; filament_type = PLA
G28
";

        var result = await _service.ExtractMetadataAsync(gcodeContent);

        result.Should().NotBeNull();
        // Should not throw and should still extract what it can
        result.Material.Should().Be("PLA");
    }
}
