<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IconGen</RootNamespace>
    <!-- Avoid generating native apphost during build which can cause copy errors on some hosts -->
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="2.0.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.8" />
    <PackageReference Include="SkiaSharp.NativeAssets.Macos" Version="3.119.1" />
  </ItemGroup>
</Project>
