import { test, expect } from '@playwright/test';
import { mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * #1788 real-worker / no-long-task smoke test.
 *
 * Every other test covering `parseGCodeDetailed` (Vitest, jsdom) stubs out
 * `Worker` with a hand-rolled fake that injects `parseDetailedLayersCore()`
 * results directly into `onmessage` — jsdom has no real OS-level worker
 * threads, so those tests never actually execute `gcodeParser.worker.ts`
 * itself, and can't observe main-thread long tasks. This spec runs in a real
 * Chromium page against the dev server and:
 *
 *   1. Dynamically imports the *production* `gcodePreviewService` module and
 *      calls the real `createGcodePreviewService().parseGCodeDetailed(url)`
 *      — the exact code that ships, constructing a real
 *      `new Worker(new URL('./gcodeParser.worker.ts', import.meta.url))`,
 *      not a fake.
 *   2. Feeds it a synthetic, sizeable G-code fixture (comparable in scale to
 *      the ~1.2M-point synthetic file from the #1766 spike that measured
 *      670-1000ms of *main-thread* parse time before this change) so a
 *      regression that moved parsing back onto the main thread would be
 *      caught.
 *   3. Uses a real `PerformanceObserver({ entryTypes: ['longtask'] })` to
 *      assert the parse produces zero main-thread long tasks — the actual
 *      acceptance criterion of #1788, which no jsdom-based test can prove.
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = resolve(__dirname, '../public/gcode-fixtures');
const POINTS_PER_LAYER = 2000;
const LAYER_COUNT = 75; // 150,000 points total

function generateSyntheticGCode(layerCount: number, pointsPerLayer: number): string {
  const lines: string[] = ['; synthetic fixture generated by gcode-worker-parse-smoke.spec.ts'];
  for (let layer = 0; layer < layerCount; layer++) {
    const z = (0.2 * (layer + 1)).toFixed(2);
    lines.push(`G1 Z${z} F3000`);
    for (let p = 0; p < pointsPerLayer; p++) {
      const x = (p % 200).toFixed(3);
      const y = (Math.floor(p / 200) % 200).toFixed(3);
      const e = (layer * pointsPerLayer + p).toFixed(4);
      lines.push(`G1 X${x} Y${y} E${e} F1500`);
    }
  }
  return lines.join('\n') + '\n';
}

test.describe('#1788 G-code Worker: real boundary + no main-thread long task', () => {
  // Every Playwright project (chromium/firefox/webkit/mobile) runs this
  // suite's beforeAll/afterAll hooks even though the test body below skips
  // non-Chromium projects — the skip only takes effect once the test starts
  // running, not before the suite hooks fire. A single shared fixture path
  // would let one project's afterAll delete the file while another
  // project's (Chromium's) test is still mid-parse reading it. Scoping the
  // fixture path to the worker/project via testInfo removes that race
  // entirely, regardless of hook/skip ordering or parallelism.
  let fixturePath: string;
  let fixtureUrl: string;

  // Playwright requires the first beforeAll/afterAll parameter to use the
  // object-destructuring fixture pattern even when no fixtures are needed;
  // only `testInfo` is used here.
  // eslint-disable-next-line no-empty-pattern
  test.beforeAll(({}, testInfo) => {
    const uniqueSuffix = `${testInfo.project.name}-${testInfo.workerIndex}`;
    fixturePath = resolve(FIXTURE_DIR, `worker-smoke-generated-${uniqueSuffix}.gcode`);
    fixtureUrl = `/gcode-fixtures/worker-smoke-generated-${uniqueSuffix}.gcode`;
    mkdirSync(FIXTURE_DIR, { recursive: true });
    writeFileSync(fixturePath, generateSyntheticGCode(LAYER_COUNT, POINTS_PER_LAYER));
  });

  test.afterAll(() => {
    if (existsSync(fixturePath)) rmSync(fixturePath);
  });

  test('parses a large synthetic G-code file through the real gcodeParser.worker.ts entrypoint without a main-thread long task', async ({ page, browserName }) => {
    // Module Workers + longtask PerformanceObserver entries are most
    // reliably supported in Chromium; one browser is sufficient to prove
    // the real worker boundary and the no-long-task acceptance criterion.
    test.skip(browserName !== 'chromium', 'Real-worker/long-task boundary only needs to be proven once, in Chromium.');

    await page.goto('/');
    // Let the initial app load settle (network requests, first React render,
    // Vite's HMR client handshake) before measuring, so one-time page-load
    // costs unrelated to G-code parsing can't bleed into the long-task
    // measurement window below.
    await page.waitForLoadState('networkidle');
    await page.evaluate(
      () => new Promise<void>((r) => requestIdleCallback(() => r(), { timeout: 3000 })),
    );

    const result = await page.evaluate(async (fixtureUrl) => {
      // Dynamically importing the real production module (served
      // unbundled by the Vite dev server) means this exercises the actual
      // shipped code path — including the real `new Worker(new URL(...))`
      // construction inside gcodePreviewService.ts — not a test double.
      // @ts-expect-error -- resolved at runtime by the Vite dev server (which
      // serves any project source file as a module), not statically
      // resolvable by tsc's module resolution.
      const mod = await import('/src/features/slicer/services/index.ts');
      const service = mod.createGcodePreviewService();
      const workerSupported = typeof Worker !== 'undefined';

      // Start observing only once the module fetch/transform/evaluation and
      // service construction are behind us, so a cold-start Vite module load
      // (which itself can register as a main-thread long task, unrelated to
      // G-code parsing) can never be misattributed to the parse under test.
      const longTaskDurations: number[] = [];
      const observer = new PerformanceObserver((list) => {
        for (const entry of list.getEntries()) longTaskDurations.push(entry.duration);
      });
      observer.observe({ entryTypes: ['longtask'] });

      const start = performance.now();
      const parsed = await service.parseGCodeDetailed(fixtureUrl);
      const elapsedMs = performance.now() - start;

      // Give the PerformanceObserver a tick to flush any buffered entries
      // before disconnecting.
      await new Promise((r) => setTimeout(r, 50));
      observer.disconnect();
      service.dispose();

      const totalPoints = parsed.layers.reduce((sum: number, l: { count: number }) => sum + l.count, 0);
      return { workerSupported, layerCount: parsed.layerCount, totalPoints, elapsedMs, longTaskDurations };
    }, fixtureUrl);

    // Sanity: the real worker path actually ran and actually parsed the
    // full fixture (not a stub returning an empty/placeholder result).
    expect(result.workerSupported).toBe(true);
    expect(result.layerCount).toBe(LAYER_COUNT);
    expect(result.totalPoints).toBe(LAYER_COUNT * (POINTS_PER_LAYER + 1)); // +1 Z-lift move per layer

    // The actual #1788/#1766 acceptance criterion: moving the parse into a
    // Worker means it never shows up as a main-thread long task, regardless
    // of how long the parse itself takes off-thread.
    expect(result.longTaskDurations).toEqual([]);
  });
});
