<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Farm.Slicer.Module.Api</RootNamespace>
    <AssemblyName>Farm.Slicer.Module.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Farm.Slicer.Module/Farm.Slicer.Module.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
