using Farm.Infrastructure.Data;
using Farm.Infrastructure.Domain;
using Farm.Infrastructure.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Farm.Infrastructure.Services.AutoTagging;

/// <summary>
/// Automatically tags completed print jobs with material type, color family, and nozzle diameter.
/// </summary>
public class AutoTagService : IAutoTagService
{
    private readonly AppDbContext _db;
    private readonly ISettingsService _settings;
    private readonly ILogger<AutoTagService> _logger;

    public AutoTagService(
        AppDbContext db,
        ISettingsService settings,
        ILogger<AutoTagService> logger)
    {
        _db = db;
        _settings = settings;
        _logger = logger;
    }

    public async Task GenerateTagsAsync(PrintJob job, Guid printerId, CancellationToken ct = default)
    {
        AutoTaggingSettings config;
        try
        {
            config = _settings.Get<AutoTaggingSettings>();
        }
        catch
        {
            // Settings not configured yet — use defaults (all enabled)
            config = new AutoTaggingSettings();
        }

        List<(string Name, string Category, string? Color)> tagsToApply = [];

        if (config.MaterialTagEnabled)
        {
            string? material = ExtractMaterial(job);
            if (material is not null)
            {
                tagsToApply.Add((material, "material", null));
            }
        }

        if (config.ColorTagEnabled && job.FilamentColor is not null)
        {
            (string familyName, string hexColor)? colorFamily = HexToColorFamily(job.FilamentColor);
            if (colorFamily is not null)
            {
                tagsToApply.Add((colorFamily.Value.familyName, "color", colorFamily.Value.hexColor));
            }
        }

        if (config.NozzleTagEnabled)
        {
            string? nozzleTag = await GetNozzleTagAsync(printerId, ct);
            if (nozzleTag is not null)
            {
                tagsToApply.Add((nozzleTag, "nozzle", null));
            }
        }

        if (tagsToApply.Count == 0)
        {
            return;
        }

        // Ensure the job's Tags collection is loaded
        if (!_db.Entry(job).Collection(j => j.Tags).IsLoaded)
        {
            await _db.Entry(job).Collection(j => j.Tags).LoadAsync(ct);
        }

        foreach ((string name, string category, string? color) in tagsToApply)
        {
            // Skip if job already has this tag
            if (job.Tags.Any(t => t.Name == name && t.Category == category))
            {
                continue;
            }

            // Find or create the tag
            Tag? tag = await _db.Tags.FirstOrDefaultAsync(
                t => t.Name == name && t.Category == category, ct);

            if (tag is null)
            {
                tag = new Tag
                {
                    Id = Guid.NewGuid(),
                    Name = name,
                    Category = category,
                    IsAutoGenerated = true,
                    Color = color,
                    CreatedAt = DateTime.UtcNow,
                    UpdatedAt = DateTime.UtcNow
                };
                _db.Tags.Add(tag);
            }

            job.Tags.Add(tag);
        }

        _logger.LogInformation(
            "[AutoTagService] Applied {Count} auto-tag(s) to job {JobId}: {Tags}",
            tagsToApply.Count,
            job.Id,
            string.Join(", ", tagsToApply.Select(t => $"{t.Category}:{t.Name}")));
    }

    /// <summary>
    /// Extracts material type from job metadata.
    /// Checks RequiredMaterialType first, then parses FilamentName.
    /// </summary>
    internal static string? ExtractMaterial(PrintJob job)
    {
        // Prefer explicit material type if set
        if (!string.IsNullOrWhiteSpace(job.RequiredMaterialType))
        {
            return NormalizeMaterial(job.RequiredMaterialType);
        }

        // Parse from filament name (e.g., "PolyTerra PLA Charcoal Black" → "PLA")
        if (!string.IsNullOrWhiteSpace(job.FilamentName))
        {
            return ParseMaterialFromName(job.FilamentName);
        }

        return null;
    }

    /// <summary>
    /// Known material keywords to search for in filament names. Ordered by specificity
    /// (longer/more-specific first to avoid "PA" matching before "PA-CF").
    /// </summary>
    private static readonly string[] KnownMaterials =
    [
        "PA-CF", "PA-GF", "PC-CF", "PET-CF", "PET-GF",
        "CF-PLA", "CF-PETG", "CF-ABS", "CF-PA", "CF-PC",
        "GF-PLA", "GF-PETG", "GF-ABS", "GF-PA",
        "PETG", "PLA+", "PLA", "ABS", "ASA", "TPU",
        "PC", "PVA", "HIPS", "Nylon", "PA",
        "PEEK", "PEI", "PCTG", "PP"
    ];

    private static string? ParseMaterialFromName(string filamentName)
    {
        foreach (string material in KnownMaterials)
        {
            if (ContainsMaterialWord(filamentName, material))
            {
                return NormalizeMaterial(material);
            }
        }

        return null;
    }

    /// <summary>
    /// Checks if the filament name contains the material as a word boundary match.
    /// Avoids false positives like "DISPLAY" matching "PLA".
    /// </summary>
    private static bool ContainsMaterialWord(string name, string material)
    {
        int idx = name.IndexOf(material, StringComparison.OrdinalIgnoreCase);
        if (idx < 0)
        {
            return false;
        }

        // Check left boundary: start of string or non-alphanumeric
        if (idx > 0 && char.IsLetterOrDigit(name[idx - 1]))
        {
            return false;
        }

        // Check right boundary: end of string or non-alphanumeric
        int endIdx = idx + material.Length;
        if (endIdx < name.Length && char.IsLetterOrDigit(name[endIdx]))
        {
            return false;
        }

        return true;
    }

    private static string NormalizeMaterial(string material)
    {
        return material.Trim().ToUpperInvariant() switch
        {
            "NYLON" => "Nylon",
            _ => material.Trim().ToUpperInvariant()
        };
    }

    /// <summary>
    /// Converts a hex color code to a color family name and representative hex.
    /// Maps to 11 families: Red, Orange, Yellow, Green, Blue, Purple, Pink, Brown, Black, White, Gray.
    /// </summary>
    internal static (string Name, string Hex)? HexToColorFamily(string hex)
    {
        hex = hex.Trim().TrimStart('#');
        if (hex.Length < 6)
        {
            return null;
        }

        if (!int.TryParse(hex[..2], System.Globalization.NumberStyles.HexNumber, null, out int r) ||
            !int.TryParse(hex[2..4], System.Globalization.NumberStyles.HexNumber, null, out int g) ||
            !int.TryParse(hex[4..6], System.Globalization.NumberStyles.HexNumber, null, out int b))
        {
            return null;
        }

        (double h, double s, double l) = RgbToHsl(r, g, b);

        // Grayscale classification
        if (s < 0.15)
        {
            if (l < 0.15)
            {
                return ("Black", "#000000");
            }

            if (l > 0.85)
            {
                return ("White", "#FFFFFF");
            }

            return ("Gray", "#808080");
        }

        // Brown detection: low-to-mid lightness, warm hue, moderate-to-high saturation
        if (l < 0.45 && h is >= 15 and < 45)
        {
            return ("Brown", "#8B4513");
        }

        // Classify by hue
        return h switch
        {
            < 15 => ("Red", "#FF0000"),
            < 45 => ("Orange", "#FF8C00"),
            < 70 => ("Yellow", "#FFD700"),
            < 165 => ("Green", "#008000"),
            < 255 => ("Blue", "#0000FF"),
            < 320 => ("Purple", "#800080"),
            < 345 => ("Pink", "#FF69B4"),
            _ => ("Red", "#FF0000")
        };
    }

    /// <summary>
    /// Converts RGB (0-255) to HSL (H: 0-360, S: 0-1, L: 0-1).
    /// </summary>
    internal static (double H, double S, double L) RgbToHsl(int r, int g, int b)
    {
        double rNorm = r / 255.0;
        double gNorm = g / 255.0;
        double bNorm = b / 255.0;

        double max = Math.Max(rNorm, Math.Max(gNorm, bNorm));
        double min = Math.Min(rNorm, Math.Min(gNorm, bNorm));
        double delta = max - min;

        double l = (max + min) / 2.0;
        double s = 0;
        double h = 0;

        if (delta > 0.0001)
        {
            s = l > 0.5
                ? delta / (2.0 - max - min)
                : delta / (max + min);

            if (Math.Abs(max - rNorm) < 0.0001)
            {
                h = ((gNorm - bNorm) / delta) + (gNorm < bNorm ? 6 : 0);
            }
            else if (Math.Abs(max - gNorm) < 0.0001)
            {
                h = ((bNorm - rNorm) / delta) + 2;
            }
            else
            {
                h = ((rNorm - gNorm) / delta) + 4;
            }

            h *= 60;
        }

        return (h, s, l);
    }

    private async Task<string?> GetNozzleTagAsync(Guid printerId, CancellationToken ct)
    {
        Toolhead? primaryToolhead = await _db.Toolheads
            .Include(t => t.NozzleModel)
            .Where(t => t.PrinterId == printerId && t.IsPrimary)
            .FirstOrDefaultAsync(ct);

        if (primaryToolhead is null)
        {
            // Fall back to any toolhead with index 0
            primaryToolhead = await _db.Toolheads
                .Include(t => t.NozzleModel)
                .Where(t => t.PrinterId == printerId && t.Index == 0)
                .FirstOrDefaultAsync(ct);
        }

        double diameter = primaryToolhead?.NozzleModel?.Diameter ?? 0;
        if (diameter <= 0)
        {
            return null;
        }

        return $"{diameter:0.##}mm";
    }
}
