using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using Farm.Infrastructure.Domain;
using Farm.Infrastructure.Repositories.Gcode;
using Farm.Infrastructure.Services.Gcode;
using Farm.Infrastructure.Services.StorageManagement;
using Farm.Infrastructure.Telemetry;
using Farm.Web.Api.Controllers;
using Farm.Web.Api.Services.FileManagement;
using Farm.Web.Api.Services.Gcode;
using Farm.Web.Api.Services.Model;
using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Moq;
using Xunit;

namespace Farm.Web.Api.Tests.Services.Gcode;

public class GcodeFilesServiceTests
{
    [Fact]
    public async Task FinalizeChunkedUploadAsync_ReturnsNullWhenFileMissingAndLogsWarning()
    {
        // Arrange
        var repo = new Mock<IGcodeRepository>(MockBehavior.Strict);
        var logger = new Mock<IUnifiedLoggingService>(MockBehavior.Strict);
        var storagePath = new Mock<IStoragePathService>(MockBehavior.Strict);
        var metadataExtractor = new Mock<IGcodeMetadataExtractorService>(MockBehavior.Strict);
        var thumbnailExtractor = new Mock<IGcodeThumbnailExtractorService>(MockBehavior.Strict);
        var chunkedUpload = new Mock<IChunkedUploadService>(MockBehavior.Strict);

        string storageDir = Path.Combine(Path.GetTempPath(), "pfarm-gcode-tests", Guid.NewGuid().ToString());
        storagePath.Setup(x => x.GetGcodeStorageDirectory()).Returns(storageDir);
        logger.Setup(x => x.LogInformation(It.IsAny<string>(), It.IsAny<string?>(), It.IsAny<object?>()));
        logger.Setup(x => x.LogWarning(It.IsAny<string>(), It.IsAny<string?>(), It.IsAny<object?>()));

        var mockModelService = new Mock<IModelService>(MockBehavior.Loose);
        var service = new GcodeFilesService(repo.Object, logger.Object, storagePath.Object, metadataExtractor.Object, thumbnailExtractor.Object, mockModelService.Object);

        // Act
        GcodeFile? result = await service.FinalizeChunkedUploadAsync(
            filePath: Path.Combine(storageDir, "missing.gcode"),
            originalFileName: "missing.gcode",
            thumbnailPath: null,
            virtualDirectory: "/jobs",
            chunkedUploadService: chunkedUpload.Object,
            ct: CancellationToken.None);

        // Assert
        result.Should().BeNull();
        repo.Verify(r => r.AddAsync(It.IsAny<GcodeFile>(), It.IsAny<CancellationToken>()), Times.Never);
        logger.Verify(x => x.LogWarning(It.IsAny<string>(), It.Is<string?>(v => v == Path.Combine(storageDir, "missing.gcode")), It.IsAny<object?>()), Times.Once);
    }

    [Fact]
    public async Task FinalizeChunkedUploadAsync_PersistsMetadataAndRenamesFiles()
    {
        // Arrange
        string storageDir = Path.Combine(Path.GetTempPath(), "pfarm-gcode-tests", Guid.NewGuid().ToString());
        Directory.CreateDirectory(storageDir);
        string sourcePath = Path.Combine(storageDir, "input.gcode");
        await File.WriteAllTextAsync(sourcePath, "G1 X1 Y1\n; generated by TestSlicer 1.0");
        string thumbnailSource = Path.Combine(storageDir, "thumb.png");
        await File.WriteAllBytesAsync(thumbnailSource, new byte[] { 1, 2, 3, 4 });

        var metadata = new GcodeMetadataExtracted
        {
            SlicerName = "TestSlicer",
            SlicerVersion = "1.0",
            NozzleDiameter = 0.4,
            Material = "PLA",
            EstimatedPrintTimeMinutes = 42,
            FilamentLengthMm = 1234,
            FilamentWeightGrams = 56
        };

        GcodeFile? added = null;
        var repo = new Mock<IGcodeRepository>(MockBehavior.Strict);
        repo.Setup(r => r.AddAsync(It.IsAny<GcodeFile>(), It.IsAny<CancellationToken>()))
            .Callback<GcodeFile, CancellationToken>((g, _) => added = g)
            .Returns(Task.CompletedTask);
        repo.Setup(r => r.SaveChangesAsync(It.IsAny<CancellationToken>())).Returns(Task.CompletedTask);

        var logger = new Mock<IUnifiedLoggingService>(MockBehavior.Loose);
        var storagePath = new Mock<IStoragePathService>(MockBehavior.Strict);
        storagePath.Setup(x => x.GetGcodeStorageDirectory()).Returns(storageDir);
        var metadataExtractor = new Mock<IGcodeMetadataExtractorService>(MockBehavior.Strict);
        var thumbnailExtractor = new Mock<IGcodeThumbnailExtractorService>(MockBehavior.Strict);
        var chunkedUpload = new Mock<IChunkedUploadService>(MockBehavior.Strict);
        chunkedUpload.Setup(c => c.ExtractMetadataFromFileAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(metadata);

        var mockModelService = new Mock<IModelService>(MockBehavior.Loose);
        var service = new GcodeFilesService(repo.Object, logger.Object, storagePath.Object, metadataExtractor.Object, thumbnailExtractor.Object, mockModelService.Object);

        // Act
        GcodeFile? result = await service.FinalizeChunkedUploadAsync(
            filePath: sourcePath,
            originalFileName: "cool-model.gcode",
            thumbnailPath: thumbnailSource,
            virtualDirectory: "/prints/models/",
            chunkedUploadService: chunkedUpload.Object,
            ct: CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        added.Should().NotBeNull();
        added!.Id.Should().NotBeEmpty();
        added.DisplayName.Should().Be("cool-model");
        added.SlicerName.Should().Be("TestSlicer");
        added.SlicerVersion.Should().Be("1.0");
        added.RequiredNozzleDiameter.Should().Be(0.4);
        added.RequiredMaterial.Should().Be("PLA");
        added.EstimatedPrintTimeMinutes.Should().Be(42);
        added.EstimatedFilamentLengthMm.Should().Be(1234);
        added.EstimatedFilamentWeightG.Should().Be(56);

        string finalGcodeName = Path.GetFileName(added.FilePath);
        finalGcodeName.Should().Be(added.Id + ".gcode");
        File.Exists(added.FilePath).Should().BeTrue();
        File.Exists(sourcePath).Should().BeFalse();

        string expectedThumb = Path.Combine(storageDir, added.Id + "_thumb.png");
        added.ThumbnailPath.Should().Be(expectedThumb);
        File.Exists(expectedThumb).Should().BeTrue();

        using FileStream fs = File.OpenRead(added.FilePath);
        using SHA256 sha = SHA256.Create();
        string expectedHash = Convert.ToHexString(await sha.ComputeHashAsync(fs, CancellationToken.None));
        added.FileHash.Should().Be(expectedHash);

        repo.Verify(r => r.AddAsync(It.IsAny<GcodeFile>(), It.IsAny<CancellationToken>()), Times.Once);
        repo.Verify(r => r.SaveChangesAsync(It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ListAsync_FiltersByHarvestAndNormalizesThumbnailUrl()
    {
        // Arrange
        string storageDir = Path.Combine(Path.GetTempPath(), "pfarm-gcode-tests", Guid.NewGuid().ToString());
        Directory.CreateDirectory(storageDir);
        string thumbPath = Path.Combine(storageDir, "thumbs", "model1.png");
        Directory.CreateDirectory(Path.GetDirectoryName(thumbPath)!);
        await File.WriteAllBytesAsync(thumbPath, new byte[] { 9, 9, 9 });

        Guid printerId = Guid.NewGuid();
        Guid harvestId = Guid.NewGuid();
        var folderJob = new Folder { Id = Guid.NewGuid(), Path = "jobs", FolderType = "gcode" };

        var dbFiles = new List<GcodeFile>
        {
            new()
            {
                Id = Guid.NewGuid(),
                OriginalFileName = "model1.gcode",
                DisplayName = "model1",
                FolderId = folderJob.Id,
                FilePath = Path.Combine(storageDir, "jobs", "model1.gcode"),
                FileSizeBytes = 1024,
                UploadedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                SourcePrinterId = printerId,
                ThumbnailPath = thumbPath
            },
            new()
            {
                Id = Guid.NewGuid(),
                OriginalFileName = "other.gcode",
                DisplayName = "other",
                FolderId = folderJob.Id,
                FilePath = Path.Combine(storageDir, "jobs", "other.gcode"),
                FileSizeBytes = 2048,
                UploadedAt = new DateTime(2024, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                SourcePrinterId = Guid.NewGuid(),
                ThumbnailPath = Path.Combine(storageDir, "thumbs", "other.png")
            }
        };

        var repo = new Mock<IGcodeRepository>(MockBehavior.Strict);
        repo.Setup(r => r.ListFilesInDirectoryAsync("jobs", It.IsAny<CancellationToken>())).ReturnsAsync(dbFiles);
        repo.Setup(r => r.ListSubdirectoriesAsync("jobs", It.IsAny<CancellationToken>())).ReturnsAsync(new List<string> { "print-jobs", ".hidden" });
        repo.Setup(r => r.GetLatestHarvestOperationIdsByPrintersAsync(It.IsAny<IEnumerable<Guid>>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new Dictionary<Guid, Guid?> { { printerId, harvestId } });

        var logger = new Mock<IUnifiedLoggingService>(MockBehavior.Loose);
        var storagePath = new Mock<IStoragePathService>(MockBehavior.Strict);
        storagePath.Setup(x => x.GetGcodeStorageDirectory()).Returns(storageDir);
        var metadataExtractor = new Mock<IGcodeMetadataExtractorService>(MockBehavior.Strict);
        var thumbnailExtractor = new Mock<IGcodeThumbnailExtractorService>(MockBehavior.Strict);
        var modelService = new Mock<IModelService>(MockBehavior.Loose);

        var service = new GcodeFilesService(repo.Object, logger.Object, storagePath.Object, metadataExtractor.Object, thumbnailExtractor.Object, modelService.Object);

        // Act
        GcodeFileListResponse response = await service.ListAsync(
            path: "/jobs",
            sortBy: "name",
            sortOrder: "asc",
            search: null,
            page: 1,
            pageSize: 10,
            harvestId: harvestId,
            printerId: null,
            ct: CancellationToken.None);

        // Assert
        response.Files.Should().HaveCount(2);
        response.TotalFiles.Should().Be(1);
        response.TotalSize.Should().Be(1024);

        GcodeFileEntryDto directoryEntry = response.Files[0];
        directoryEntry.IsDirectory.Should().BeTrue();
        directoryEntry.Name.Should().Be("print-jobs");
        directoryEntry.Path.Should().Be("/jobs/print-jobs");

        GcodeFileEntryDto fileEntry = response.Files[1];
        fileEntry.IsDirectory.Should().BeFalse();
        fileEntry.Name.Should().Be("model1.gcode");
        fileEntry.Path.Should().Be("/jobs/model1.gcode");
        fileEntry.HarvestOperationId.Should().Be(harvestId);
        fileEntry.ThumbnailPath.Should().Be("/api/gcode-files/download?path=thumbs%2Fmodel1.png");
    }
}
