using Farm.Infrastructure.Data;
using Farm.Infrastructure.Services.ServerIdentity;
using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Moq;
using Xunit;

namespace Farm.Web.Api.Tests.Services.ServerIdentity;

/// <summary>
/// Verifies <see cref="ServerIdentityService"/>: the origin-server identity backing
/// APNs' <c>originServerId</c> (#1407) is generated once, persisted via the generic
/// <c>AppSettingsEntity</c> table, stable across restarts (new DbContexts against the
/// same store), converges under a concurrent first-call race, and is distinct per
/// isolated database.
/// </summary>
public sealed class ServerIdentityServiceTests : IDisposable
{
    private readonly SqliteConnection _connection;
    private readonly DbContextOptions<AppDbContext> _options;

    public ServerIdentityServiceTests()
    {
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();

        _options = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite(_connection)
            .Options;

        using AppDbContext db = new(_options);
        _ = db.Database.EnsureCreated();
    }

    public void Dispose()
    {
        _connection.Dispose();
        GC.SuppressFinalize(this);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_FirstCall_GeneratesAndPersistsNonEmptyGuid()
    {
        ServerIdentityService sut = CreateService();

        Guid serverId = await sut.GetOrCreateServerIdAsync();

        serverId.Should().NotBe(Guid.Empty);

        using AppDbContext db = new(_options);
        AppSettingsEntity? row = await db.AppSettingsEntities
            .FirstOrDefaultAsync(e => e.Key == ServerIdentityService.SettingsKey);
        row.Should().NotBeNull();
        row!.SettingsJson.Should().Contain(serverId.ToString());
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_CalledTwiceOnSameInstance_ReturnsSameCachedValue()
    {
        ServerIdentityService sut = CreateService();

        Guid first = await sut.GetOrCreateServerIdAsync();
        Guid second = await sut.GetOrCreateServerIdAsync();

        second.Should().Be(first);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_NewServiceInstance_ReadsSamePersistedValue()
    {
        // Simulates a process restart: a brand-new ServerIdentityService instance (fresh
        // in-memory cache) reading against the same underlying database must observe the
        // identity generated by an earlier instance rather than regenerating it.
        ServerIdentityService first = CreateService();
        Guid generated = await first.GetOrCreateServerIdAsync();

        ServerIdentityService restarted = CreateService();
        Guid afterRestart = await restarted.GetOrCreateServerIdAsync();

        afterRestart.Should().Be(generated);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_ConcurrentFirstCalls_ConvergeOnSingleValue()
    {
        ServerIdentityService sut = CreateService();

        Task<Guid>[] racers = Enumerable.Range(0, 16)
            .Select(_ => sut.GetOrCreateServerIdAsync())
            .ToArray();
        Guid[] results = await Task.WhenAll(racers);

        results.Distinct().Should().ContainSingle();
        results[0].Should().NotBe(Guid.Empty);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_TwoIsolatedDatabases_ProduceDistinctIdentities()
    {
        ServerIdentityService serviceA = CreateService();

        using SqliteConnection connectionB = new("DataSource=:memory:");
        connectionB.Open();
        DbContextOptions<AppDbContext> optionsB = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite(connectionB)
            .Options;
        using (AppDbContext dbB = new(optionsB))
        {
            _ = dbB.Database.EnsureCreated();
        }

        Mock<IDbContextFactory<AppDbContext>> factoryMockB = new();
        _ = factoryMockB.Setup(f => f.CreateDbContextAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(() => new AppDbContext(optionsB));
        ServerIdentityService serviceB = new(factoryMockB.Object);

        Guid idA = await serviceA.GetOrCreateServerIdAsync();
        Guid idB = await serviceB.GetOrCreateServerIdAsync();

        idA.Should().NotBe(idB);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_CorruptPersistedRow_RepairsInPlaceWithNewIdentity()
    {
        using (AppDbContext seed = new(_options))
        {
            seed.AppSettingsEntities.Add(new AppSettingsEntity
            {
                Key = ServerIdentityService.SettingsKey,
                SettingsJson = "not valid json",
                UpdatedAt = DateTime.UtcNow,
            });
            _ = await seed.SaveChangesAsync();
        }

        ServerIdentityService sut = CreateService();

        Guid repaired = await sut.GetOrCreateServerIdAsync();

        repaired.Should().NotBe(Guid.Empty);

        using AppDbContext db = new(_options);
        AppSettingsEntity? row = await db.AppSettingsEntities
            .FirstOrDefaultAsync(e => e.Key == ServerIdentityService.SettingsKey);
        row.Should().NotBeNull();
        row!.SettingsJson.Should().Contain(repaired.ToString());
    }

    private ServerIdentityService CreateService()
    {
        Mock<IDbContextFactory<AppDbContext>> factoryMock = new();
        _ = factoryMock.Setup(f => f.CreateDbContextAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(() => new AppDbContext(_options));
        return new ServerIdentityService(factoryMock.Object);
    }
}
