using Farm.Infrastructure.Data;
using Farm.Infrastructure.Services.ServerIdentity;
using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Moq;
using Xunit;

namespace Farm.Web.Api.Tests.Services.ServerIdentity;

/// <summary>
/// Verifies <see cref="ServerIdentityService"/>: the origin-server identity backing
/// APNs' <c>originServerId</c> (#1407) is generated once, persisted via the generic
/// <c>AppSettingsEntity</c> table, stable across restarts (new DbContexts against the
/// same store), converges under a concurrent first-call race, and is distinct per
/// isolated database.
/// </summary>
public sealed class ServerIdentityServiceTests : IDisposable
{
    private readonly SqliteConnection _connection;
    private readonly DbContextOptions<AppDbContext> _options;

    public ServerIdentityServiceTests()
    {
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();

        _options = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite(_connection)
            .Options;

        using AppDbContext db = new(_options);
        _ = db.Database.EnsureCreated();
    }

    public void Dispose()
    {
        _connection.Dispose();
        GC.SuppressFinalize(this);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_FirstCall_GeneratesAndPersistsNonEmptyGuid()
    {
        ServerIdentityService sut = CreateService();

        Guid serverId = await sut.GetOrCreateServerIdAsync();

        serverId.Should().NotBe(Guid.Empty);

        using AppDbContext db = new(_options);
        AppSettingsEntity? row = await db.AppSettingsEntities
            .FirstOrDefaultAsync(e => e.Key == ServerIdentityService.SettingsKey);
        row.Should().NotBeNull();
        row!.SettingsJson.Should().Contain(serverId.ToString());
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_CalledTwiceOnSameInstance_ReturnsSameCachedValue()
    {
        ServerIdentityService sut = CreateService();

        Guid first = await sut.GetOrCreateServerIdAsync();
        Guid second = await sut.GetOrCreateServerIdAsync();

        second.Should().Be(first);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_NewServiceInstance_ReadsSamePersistedValue()
    {
        // Simulates a process restart: a brand-new ServerIdentityService instance (fresh
        // in-memory cache) reading against the same underlying database must observe the
        // identity generated by an earlier instance rather than regenerating it.
        ServerIdentityService first = CreateService();
        Guid generated = await first.GetOrCreateServerIdAsync();

        ServerIdentityService restarted = CreateService();
        Guid afterRestart = await restarted.GetOrCreateServerIdAsync();

        afterRestart.Should().Be(generated);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_ConcurrentFirstCalls_ConvergeOnSingleValue()
    {
        ServerIdentityService sut = CreateService();

        Task<Guid>[] racers = Enumerable.Range(0, 16)
            .Select(_ => sut.GetOrCreateServerIdAsync())
            .ToArray();
        Guid[] results = await Task.WhenAll(racers);

        results.Distinct().Should().ContainSingle();
        results[0].Should().NotBe(Guid.Empty);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_TwoInstancesSameDatabase_RaceConvergesOnSingleValue()
    {
        // Unlike the same-instance race above (which never leaves the in-memory
        // semaphore), this races two *separate* ServerIdentityService instances against
        // the same underlying database, forcing one insert to lose the unique-index race
        // and take the DbUpdateException -> detach -> re-read retry path.
        ServerIdentityService instanceA = CreateService();
        ServerIdentityService instanceB = CreateService();

        Guid[] results = await Task.WhenAll(
            instanceA.GetOrCreateServerIdAsync(),
            instanceB.GetOrCreateServerIdAsync());

        results.Distinct().Should().ContainSingle();
        results[0].Should().NotBe(Guid.Empty);

        using AppDbContext db = new(_options);
        List<AppSettingsEntity> rows = await db.AppSettingsEntities
            .Where(e => e.Key == ServerIdentityService.SettingsKey)
            .ToListAsync();
        rows.Should().ContainSingle();
        rows[0].SettingsJson.Should().Contain(results[0].ToString());
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_TwoInstancesRaceOnCorruptRow_ConvergeOnSingleRepairedValue()
    {
        // Both instances observe the same corrupt row and race to repair it. The fix for
        // #1407's review feedback re-checks the row immediately before overwriting, so the
        // loser must return the winner's repaired value instead of clobbering it with its
        // own speculative Guid.
        using (AppDbContext seed = new(_options))
        {
            seed.AppSettingsEntities.Add(new AppSettingsEntity
            {
                Key = ServerIdentityService.SettingsKey,
                SettingsJson = "not valid json",
                UpdatedAt = DateTime.UtcNow,
            });
            _ = await seed.SaveChangesAsync();
        }

        ServerIdentityService instanceA = CreateService();
        ServerIdentityService instanceB = CreateService();

        Guid[] results = await Task.WhenAll(
            instanceA.GetOrCreateServerIdAsync(),
            instanceB.GetOrCreateServerIdAsync());

        results.Distinct().Should().ContainSingle();
        results[0].Should().NotBe(Guid.Empty);

        using AppDbContext db = new(_options);
        List<AppSettingsEntity> rows = await db.AppSettingsEntities
            .Where(e => e.Key == ServerIdentityService.SettingsKey)
            .ToListAsync();
        rows.Should().ContainSingle();
        rows[0].SettingsJson.Should().Contain(results[0].ToString());
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_EmptyGuidPersistedRow_RepairsInPlaceWithNewIdentity()
    {
        // A well-formed payload whose ServerId is Guid.Empty must be treated the same as
        // corrupt/unparseable JSON: never trusted as a stable identity, always repaired.
        using (AppDbContext seed = new(_options))
        {
            seed.AppSettingsEntities.Add(new AppSettingsEntity
            {
                Key = ServerIdentityService.SettingsKey,
                SettingsJson = """{"ServerId":"00000000-0000-0000-0000-000000000000"}""",
                UpdatedAt = DateTime.UtcNow,
            });
            _ = await seed.SaveChangesAsync();
        }

        ServerIdentityService sut = CreateService();

        Guid repaired = await sut.GetOrCreateServerIdAsync();

        repaired.Should().NotBe(Guid.Empty);

        using AppDbContext db = new(_options);
        AppSettingsEntity? row = await db.AppSettingsEntities
            .FirstOrDefaultAsync(e => e.Key == ServerIdentityService.SettingsKey);
        row.Should().NotBeNull();
        row!.SettingsJson.Should().Contain(repaired.ToString());
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_TwoIsolatedDatabases_ProduceDistinctIdentities()
    {
        ServerIdentityService serviceA = CreateService();

        using SqliteConnection connectionB = new("DataSource=:memory:");
        connectionB.Open();
        DbContextOptions<AppDbContext> optionsB = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite(connectionB)
            .Options;
        using (AppDbContext dbB = new(optionsB))
        {
            _ = dbB.Database.EnsureCreated();
        }

        Mock<IDbContextFactory<AppDbContext>> factoryMockB = new();
        _ = factoryMockB.Setup(f => f.CreateDbContextAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(() => new AppDbContext(optionsB));
        ServerIdentityService serviceB = new(factoryMockB.Object);

        Guid idA = await serviceA.GetOrCreateServerIdAsync();
        Guid idB = await serviceB.GetOrCreateServerIdAsync();

        idA.Should().NotBe(idB);
    }

    [Fact]
    public async Task GetOrCreateServerIdAsync_CorruptPersistedRow_RepairsInPlaceWithNewIdentity()
    {
        using (AppDbContext seed = new(_options))
        {
            seed.AppSettingsEntities.Add(new AppSettingsEntity
            {
                Key = ServerIdentityService.SettingsKey,
                SettingsJson = "not valid json",
                UpdatedAt = DateTime.UtcNow,
            });
            _ = await seed.SaveChangesAsync();
        }

        ServerIdentityService sut = CreateService();

        Guid repaired = await sut.GetOrCreateServerIdAsync();

        repaired.Should().NotBe(Guid.Empty);

        using AppDbContext db = new(_options);
        AppSettingsEntity? row = await db.AppSettingsEntities
            .FirstOrDefaultAsync(e => e.Key == ServerIdentityService.SettingsKey);
        row.Should().NotBeNull();
        row!.SettingsJson.Should().Contain(repaired.ToString());
    }

    private ServerIdentityService CreateService()
    {
        Mock<IDbContextFactory<AppDbContext>> factoryMock = new();
        _ = factoryMock.Setup(f => f.CreateDbContextAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(() => new AppDbContext(_options));
        return new ServerIdentityService(factoryMock.Object);
    }
}
