// ============================================================================
// Maintenance Module TypeScript Interfaces
// Mirrors C# domain models and API DTOs for printer maintenance functionality
// ============================================================================

// ============================================================================
// Domain Models (from Farm.Infrastructure.Domain)
// ============================================================================

/**
 * Status of a maintenance alert
 */
export enum MaintenanceAlertStatus {
  Active = 0,
  Acknowledged = 1,
  Resolved = 2,
  Dismissed = 3
}

/**
 * Represents an active maintenance alert that requires attention.
 * Generated by the MaintenanceAlertEngine based on printer statistics and maintenance schedules.
 */
export interface MaintenanceAlert {
  id: string;
  printerId: string;
  /**
   * Optional physical toolhead scope (see issue #711/#719). When present the
   * alert applies to a single toolhead on the printer; when `null`/omitted the
   * alert is printer-wide, which preserves legacy records. MMU/AMS gates are
   * never a valid maintenance toolhead scope.
   */
  toolheadId?: string | null;
  printerMaintenanceScheduleId?: string | null;
  maintenanceTaskId?: string | null;
  title: string;
  message: string;
  severity: number; // 1=Low, 2=Medium, 3=High, 4=Critical
  status: MaintenanceAlertStatus;
  printerHoursAtTrigger: number;
  hoursSinceLastMaintenance?: number | null;
  daysSinceLastMaintenance?: number | null;
  createdAt: string; // ISO 8601 datetime
  acknowledgedAt?: string | null;
  acknowledgedBy?: string | null;
  resolvedAt?: string | null;
  resolvedBy?: string | null;
  dismissedAt?: string | null;
  dismissedBy?: string | null;
  dismissalReason?: string | null;
  updatedAt: string;
  // Navigation properties (optional for API responses)
  printer?: Record<string, unknown>; // Printer entity reference
  printerMaintenanceSchedule?: Record<string, unknown>;
  maintenanceTask?: Record<string, unknown>;
}

/**
 * Records a completed maintenance activity on a printer.
 * Provides audit trail and history for maintenance operations.
 */
export interface MaintenanceLog {
  id: string;
  printerId: string;
  /**
   * Optional physical toolhead scope. `null` (or omitted) means the log applies
   * to the printer as a whole — legacy records preserve this behaviour.
   */
  toolheadId?: string | null;
  printerMaintenanceScheduleId?: string | null;
  maintenanceTaskId?: string | null;
  resolvedAlertId?: string | null;
  taskName: string;
  notes?: string | null;
  component?: string | null;
  performedBy?: string | null;
  performedAt: string; // ISO 8601 datetime
  durationMinutes?: number | null;
  partsReplaced?: string | null;
  cost?: number | null;
  printerHoursAtMaintenance?: number | null;
  createdAt: string;
  // Navigation properties (optional)
  printer?: Record<string, unknown>;
  printerMaintenanceSchedule?: Record<string, unknown>;
  maintenanceTask?: Record<string, unknown>;
  resolvedAlert?: MaintenanceAlert;
}

/**
 * Stores cumulative statistics for a printer (external + internal prints).
 * One-to-one relationship with Printer.
 */
export interface PrinterStatistics {
  id: string;
  printerId: string;
  totalPrintHours: number; // Cumulative print time in hours
  totalJobsCompleted: number; // Total number of completed print jobs
  totalJobsFailed: number; // Total number of failed print jobs
  totalFilamentUsedGrams: number; // Total filament used in grams
  totalFilamentUsedMeters: number; // Total filament used in meters
  lastSyncTime: string; // ISO 8601 datetime - when stats were last updated
  createdAt: string;
  updatedAt: string;
}

/**
 * Fleet-wide printer statistics with maintenance projections.
 * Returned by GET /api/maintenance/statistics/fleet
 */
export interface FleetPrinterStatistics {
  printerId: string;
  printerName: string;
  manufacturerName?: string | null;
  modelName?: string | null;
  isOnline: boolean;
  inMaintenance: boolean;
  totalPrintHours: number;
  totalJobsCompleted: number;
  totalJobsFailed: number;
  totalFilamentUsedGrams: number;
  totalFilamentUsedMeters: number;
  lastSyncTime?: string | null;
  /** Days until next maintenance task is due (negative = overdue) */
  daysUntilNextMaintenance?: number | null;
  /** Name of the next maintenance task due */
  nextMaintenanceTask?: string | null;
}

// ============================================================================
// API Request DTOs (from MaintenanceController)
// ============================================================================

export interface AcknowledgeAlertRequest {
  acknowledgedBy: string;
}

export interface DismissAlertRequest {
  dismissedBy: string;
  reason?: string | null;
}

export interface ResolveAlertRequest {
  performedBy: string;
  notes?: string | null;
  durationMinutes?: number | null;
  cost?: number | null;
  partsReplaced?: string | null;
}

export interface CreateMaintenanceLogRequest {
  printerId: string;
  /**
   * Optional physical toolhead scope. Omit or set `null` for printer-wide logs.
   * MMU/AMS gate toolheads must never be sent as a scope.
   */
  toolheadId?: string | null;
  deploymentId?: string | null;
  taskId?: string | null;
  taskName?: string | null;
  componentName?: string | null;
  performedAt?: string | null; // ISO 8601 datetime
  performedBy: string;
  notes?: string | null;
  durationMinutes?: number | null;
  cost?: number | null;
  partsReplaced?: string | null;
}

export interface UpdateMaintenanceModeRequest {
  inMaintenance: boolean;
}

// ============================================================================
// API Response DTOs
// ============================================================================

export interface ResolveAlertResponse {
  alert: MaintenanceAlert;
  maintenanceLog: MaintenanceLog;
}

// ============================================================================
// SignalR Event Payloads
// ============================================================================

export interface AlertCreatedEvent {
  id: string;
  printerId: string;
  scheduleId: string;
  title: string;
  message: string;
  severity: number;
  createdAt: string;
}

export interface AlertStatusChangedEvent {
  id: string;
  printerId: string;
  status: string; // Enum as string
  acknowledgedAt?: string | null;
  acknowledgedBy?: string | null;
  resolvedAt?: string | null;
  resolvedBy?: string | null;
  dismissedAt?: string | null;
  dismissedBy?: string | null;
  dismissalReason?: string | null;
}

export interface MaintenanceCompletedEvent {
  logId: string;
  printerId: string;
  /** Optional physical toolhead scope carried on lowercase realtime events. */
  toolheadId?: string | null;
  scheduleId?: string | null;
  performedAt: string;
  performedBy?: string | null;
}

// ============================================================================
// Per-toolhead odometers (#711/#719)
// ============================================================================

/**
 * Per-physical-toolhead odometer displayed on the printer maintenance page.
 *
 * There is no dedicated backend endpoint. The #711 stable contract
 * (`jpapiez-squad-711-fallback-maintenance-backend` @ `0bfa50343`) surfaces
 * per-tool cumulative print hours directly on `PrinterDetailsDto.toolheads[]`
 * as `cumulativePrintHours`. This client-side shape is assembled by the
 * printer maintenance page from that field plus due state derived from the
 * upcoming-maintenance feed joined by `toolheadId` (the schedule engine's own
 * verdict — alert severity is task priority, not timing).
 */
export interface PrinterToolheadOdometer {
  toolheadId: string;
  toolheadName?: string | null;
  toolheadIndex?: number | null;
  /**
   * Cumulative print hours accrued while this toolhead was the active tool,
   * from `PrinterDetailsDto.toolheads[i].cumulativePrintHours`. Null when
   * the backend has not yet observed any per-tool activity for the toolhead
   * (e.g. brand-new printer or non-attributable topology).
   */
  cumulativePrintHours?: number | null;
  /**
   * True when the upcoming-maintenance feed reports this toolhead has at
   * least one overdue task. Only meaningful when `dueStateUnavailable` is
   * false; otherwise callers should treat this as unknown.
   */
  isOverdue?: boolean;
  /**
   * True when the upcoming-maintenance feed reports this toolhead has at
   * least one task due today (and none overdue). Only meaningful when
   * `dueStateUnavailable` is false.
   */
  isDueToday?: boolean;
  /** Optional soonest-due summary derived from the upcoming feed. */
  nextDueTaskName?: string | null;
  /**
   * True when the upcoming-maintenance feed is loading or errored, so due
   * state (`isOverdue`/`isDueToday`) cannot be determined. UIs must render
   * an unknown/loading indicator instead of "OK" — a failed schedule query
   * would otherwise give operators a false all-clear.
   */
  dueStateUnavailable?: boolean;
}

// ============================================================================
// Hierarchical Maintenance Plan Types (V3 architecture)
// Task (global catalog) → Plan (curated task bundle via PlanTask) → Schedule (deployment)
// ============================================================================

/**
 * A global maintenance task in the catalog.
 * Tasks exist independently and can be reused across multiple plans.
 */
export interface MaintenanceTaskDto {
  id: string;
  taskName: string;
  description?: string | null;
  category: string;
  intervalHours?: number | null;
  intervalDays?: number | null;
  estimatedDurationMinutes?: number | null;
  priority: number;
  isActive: boolean;
  isDefault: boolean;
  // Scope rules — nullable booleans indicating which printer features require this task
  requiresEnclosure?: boolean | null;
  requiresCarbonFilter?: boolean | null;
  requiresHepaFilter?: boolean | null;
  requiresBowdenTube?: boolean | null;
  requiresPtfeLiner?: boolean | null;
  requiresLinearRails?: boolean | null;
  requiresLeadScrews?: boolean | null;
  requiresToolchanger?: boolean | null;
  requiresFilamentCutter?: boolean | null;
  requiresHeatedChamber?: boolean | null;
  requiresHeatedBed?: boolean | null;
  requiresMultiMaterial?: boolean | null;
  createdAt: string;
  updatedAt: string;
  taskComponents: MaintenanceTaskComponentDto[];
}

/**
 * Join entity linking a task to a plan, with optional sort order and interval overrides.
 */
export interface PlanTaskDto {
  id: string;
  maintenancePlanId: string;
  maintenanceTaskId: string;
  sortOrder: number;
  intervalHoursOverride?: number | null;
  intervalDaysOverride?: number | null;
  task: MaintenanceTaskDto;
}

/**
 * A maintenance plan groups related tasks for a printer, model, manufacturer, or motion type.
 */
export interface MaintenancePlanDto {
  id: string;
  name: string;
  description?: string | null;
  printerId?: string | null;
  printerName?: string | null;
  printerModelId?: string | null;
  printerModelName?: string | null;
  manufacturerId?: string | null;
  manufacturerName?: string | null;
  motionType?: number | null;
  isActive: boolean;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
  planTasks: PlanTaskDto[];
}

/**
 * Junction linking a task to a component with quantity.
 */
export interface MaintenanceTaskComponentDto {
  id: string;
  maintenanceTaskId: string;
  maintenanceComponentId: string;
  componentName?: string | null;
  quantity: number;
  notes?: string | null;
}

/**
 * A physical component/part in the global inventory.
 */
export interface MaintenanceComponentDto {
  id: string;
  name: string;
  sku?: string | null;
  description?: string | null;
  category: string;
  unitCost?: number | null;
  supplier?: string | null;
  url?: string | null;
  inStock: number;
  minimumStock: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * A maintenance plan deployed to a specific printer.
 */
export interface PrinterMaintenanceScheduleDto {
  id: string;
  maintenancePlanId: string;
  planName: string;
  printerId: string;
  printerName?: string | null;
  /**
   * Optional physical toolhead scope. `null`/omitted means the plan is
   * deployed printer-wide (legacy behaviour).
   */
  toolheadId?: string | null;
  /** Human-readable name of the scoped toolhead when the API resolves it. */
  toolheadName?: string | null;
  isActive: boolean;
  deployedAt: string;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

// ============================================================================
// Request DTOs for hierarchical maintenance plans
// ============================================================================

export interface CreateMaintenancePlanDto {
  name: string;
  description?: string | null;
  printerId?: string | null;
  printerModelId?: string | null;
  manufacturerId?: string | null;
  motionType?: number | null;
  isActive?: boolean;
  isDefault?: boolean;
}

export interface UpdateMaintenancePlanDto {
  name: string;
  description?: string | null;
  printerId?: string | null;
  printerModelId?: string | null;
  manufacturerId?: string | null;
  motionType?: number | null;
  isActive?: boolean;
  isDefault?: boolean;
}

export interface CreateMaintenanceTaskDto {
  taskName: string;
  category: string;
  description?: string | null;
  intervalHours?: number | null;
  intervalDays?: number | null;
  estimatedDurationMinutes?: number | null;
  priority?: number;
  isActive?: boolean;
  isDefault?: boolean;
  requiresEnclosure?: boolean | null;
  requiresCarbonFilter?: boolean | null;
  requiresHepaFilter?: boolean | null;
  requiresBowdenTube?: boolean | null;
  requiresPtfeLiner?: boolean | null;
  requiresLinearRails?: boolean | null;
  requiresLeadScrews?: boolean | null;
  requiresToolchanger?: boolean | null;
  requiresFilamentCutter?: boolean | null;
  requiresHeatedChamber?: boolean | null;
  requiresHeatedBed?: boolean | null;
  requiresMultiMaterial?: boolean | null;
}

export interface UpdateMaintenanceTaskDto {
  taskName: string;
  category: string;
  description?: string | null;
  intervalHours?: number | null;
  intervalDays?: number | null;
  estimatedDurationMinutes?: number | null;
  priority?: number;
  isActive?: boolean;
  isDefault?: boolean;
  requiresEnclosure?: boolean | null;
  requiresCarbonFilter?: boolean | null;
  requiresHepaFilter?: boolean | null;
  requiresBowdenTube?: boolean | null;
  requiresPtfeLiner?: boolean | null;
  requiresLinearRails?: boolean | null;
  requiresLeadScrews?: boolean | null;
  requiresToolchanger?: boolean | null;
  requiresFilamentCutter?: boolean | null;
  requiresHeatedChamber?: boolean | null;
  requiresHeatedBed?: boolean | null;
  requiresMultiMaterial?: boolean | null;
}

export interface AddTaskComponentDto {
  componentId: string;
  quantity?: number;
  notes?: string | null;
}

export interface DeployMaintenancePlanDto {
  maintenancePlanId: string;
  printerId: string;
  /**
   * Optional physical toolhead scope. Omit for printer-wide deployment.
   * See per-toolhead maintenance work (#711/#719).
   */
  toolheadId?: string | null;
  notes?: string | null;
}

export interface UpdateScheduleDeploymentDto {
  isActive: boolean;
  notes?: string | null;
}

export interface CreateMaintenanceComponentDto {
  name: string;
  category: string;
  sku?: string | null;
  description?: string | null;
  unitCost?: number | null;
  supplier?: string | null;
  url?: string | null;
  inStock?: number;
  minimumStock?: number;
}

export interface UpdateMaintenanceComponentDto {
  name: string;
  category: string;
  sku?: string | null;
  description?: string | null;
  unitCost?: number | null;
  supplier?: string | null;
  url?: string | null;
  inStock?: number;
  minimumStock?: number;
}

// ============================================================================
// Import / Export DTOs
// ============================================================================

export interface MaintenanceImportResult {
  createdCount: number;
  updatedCount: number;
  errorCount: number;
  errors: string[];
  warnings: string[];
}

export interface MaintenanceExportEnvelope {
  version: number;
  exportType: string;
  exportedAt: string;
  components?: ComponentExportDto[];
  tasks?: TaskExportDto[];
  plans?: PlanExportDto[];
}

export interface ComponentExportDto {
  name: string;
  category: string;
  sku?: string | null;
  description?: string | null;
  unitCost?: number | null;
  supplier?: string | null;
  url?: string | null;
  inStock: number;
  minimumStock: number;
}

export interface TaskExportDto {
  taskName: string;
  category: string;
  description?: string | null;
  intervalHours?: number | null;
  intervalDays?: number | null;
  estimatedDurationMinutes?: number | null;
  priority: number;
  isActive: boolean;
  components?: TaskComponentRefDto[];
}

export interface TaskComponentRefDto {
  name: string;
  quantity: number;
  notes?: string | null;
}

export interface PlanExportDto {
  name: string;
  description?: string | null;
  isActive: boolean;
  tasks?: PlanTaskRefDto[];
}

export interface PlanTaskRefDto {
  taskName: string;
  sortOrder: number;
  intervalHoursOverride?: number | null;
  intervalDaysOverride?: number | null;
}
