// ============================================================================
// Maintenance Module TypeScript Interfaces
// Mirrors C# domain models and API DTOs for printer maintenance functionality
// ============================================================================

// ============================================================================
// Domain Models (from Farm.Infrastructure.Domain)
// ============================================================================

/**
 * Status of a maintenance alert
 */
export enum MaintenanceAlertStatus {
  Active = 0,
  Acknowledged = 1,
  Resolved = 2,
  Dismissed = 3
}

/**
 * Represents an active maintenance alert that requires attention.
 * Generated by the MaintenanceAlertEngine based on printer statistics and maintenance schedules.
 */
export interface MaintenanceAlert {
  id: string;
  printerId: string;
  maintenanceScheduleId: string;
  title: string;
  message: string;
  severity: number; // 1=Low, 2=Medium, 3=High, 4=Critical
  status: MaintenanceAlertStatus;
  printerHoursAtTrigger: number;
  hoursSinceLastMaintenance?: number | null;
  daysSinceLastMaintenance?: number | null;
  createdAt: string; // ISO 8601 datetime
  acknowledgedAt?: string | null;
  acknowledgedBy?: string | null;
  resolvedAt?: string | null;
  resolvedBy?: string | null;
  dismissedAt?: string | null;
  dismissedBy?: string | null;
  dismissalReason?: string | null;
  updatedAt: string;
  // Navigation properties (optional for API responses)
  printer?: Record<string, unknown>; // Printer entity reference
  maintenanceSchedule?: MaintenanceSchedule;
}

/**
 * Defines a maintenance task and its interval/threshold for a specific printer.
 * Can be model-specific (seeded for all printers of a model) or printer-specific (custom per printer).
 */
export interface MaintenanceSchedule {
  id: string;
  printerId?: string | null;
  printerModelId?: string | null;
  manufacturerId?: string | null;
  motionType?: number | null;
  taskName: string;
  description?: string | null;
  component?: string | null; // e.g., "Hotend", "Bed", "Belts", "Bearings", "Fans"
  intervalHours?: number | null; // Maintenance interval in print hours
  intervalDays?: number | null; // Maintenance interval in calendar days
  estimatedDurationMinutes?: number | null;
  priority: number; // 1=Low, 2=Medium, 3=High, 4=Critical
  isActive: boolean;
  isDefault: boolean; // Seeded for all printers of this model
  createdAt: string;
  updatedAt: string;
  // Navigation properties (optional)
  printer?: Record<string, unknown>;
  printerModel?: Record<string, unknown>;
}

/**
 * Records a completed maintenance activity on a printer.
 * Provides audit trail and history for maintenance operations.
 */
export interface MaintenanceLog {
  id: string;
  printerId: string;
  maintenanceScheduleId?: string | null;
  resolvedAlertId?: string | null;
  taskName: string;
  notes?: string | null;
  component?: string | null;
  performedBy?: string | null;
  performedAt: string; // ISO 8601 datetime
  durationMinutes?: number | null;
  partsReplaced?: string | null;
  cost?: number | null;
  printerHoursAtMaintenance?: number | null;
  createdAt: string;
  // Navigation properties (optional)
  printer?: Record<string, unknown>;
  maintenanceSchedule?: MaintenanceSchedule;
  resolvedAlert?: MaintenanceAlert;
}

/**
 * Stores cumulative statistics for a printer (external + internal prints).
 * One-to-one relationship with Printer.
 */
export interface PrinterStatistics {
  id: string;
  printerId: string;
  totalPrintHours: number; // Cumulative print time in hours
  totalJobsCompleted: number; // Total number of completed print jobs
  totalJobsFailed: number; // Total number of failed print jobs
  totalFilamentUsedGrams: number; // Total filament used in grams
  totalFilamentUsedMeters: number; // Total filament used in meters
  lastSyncTime: string; // ISO 8601 datetime - when stats were last updated
  createdAt: string;
  updatedAt: string;
}

/**
 * Fleet-wide printer statistics with maintenance projections.
 * Returned by GET /api/maintenance/statistics/fleet
 */
export interface FleetPrinterStatistics {
  printerId: string;
  printerName: string;
  manufacturerName?: string | null;
  modelName?: string | null;
  isOnline: boolean;
  inMaintenance: boolean;
  totalPrintHours: number;
  totalJobsCompleted: number;
  totalJobsFailed: number;
  totalFilamentUsedGrams: number;
  totalFilamentUsedMeters: number;
  lastSyncTime?: string | null;
  /** Days until next maintenance task is due (negative = overdue) */
  daysUntilNextMaintenance?: number | null;
  /** Name of the next maintenance task due */
  nextMaintenanceTask?: string | null;
}

// ============================================================================
// API Request DTOs (from MaintenanceController)
// ============================================================================

export interface AcknowledgeAlertRequest {
  acknowledgedBy: string;
}

export interface DismissAlertRequest {
  dismissedBy: string;
  reason?: string | null;
}

export interface ResolveAlertRequest {
  performedBy: string;
  notes?: string | null;
  durationMinutes?: number | null;
  cost?: number | null;
  partsReplaced?: string | null;
}

export interface CreateMaintenanceLogRequest {
  printerId: string;
  scheduleId?: string | null;
  taskName?: string | null;
  componentName?: string | null;
  performedAt?: string | null; // ISO 8601 datetime
  performedBy: string;
  notes?: string | null;
  durationMinutes?: number | null;
  cost?: number | null;
  partsReplaced?: string | null;
}

export interface CreateMaintenanceScheduleRequest {
  taskName: string;
  description?: string | null;
  intervalHours?: number | null;
  intervalDays?: number | null;
  componentName?: string | null;
  printerModelId?: string | null;
  printerId?: string | null;
  isActive?: boolean | null;
}

export interface BulkScheduleOperationResponse {
  printersProcessed: number;
  schedulesCreated: number;
  schedulesUpdated: number;
  schedulesSkipped: number;
}

export interface UpdateMaintenanceScheduleRequest {
  taskName?: string | null;
  description?: string | null;
  intervalHours?: number | null;
  intervalDays?: number | null;
  componentName?: string | null;
  isActive?: boolean | null;
}

export interface UpdateMaintenanceModeRequest {
  inMaintenance: boolean;
}

// ============================================================================
// API Response DTOs
// ============================================================================

export interface ResolveAlertResponse {
  alert: MaintenanceAlert;
  maintenanceLog: MaintenanceLog;
}

// ============================================================================
// SignalR Event Payloads
// ============================================================================

export interface AlertCreatedEvent {
  id: string;
  printerId: string;
  scheduleId: string;
  title: string;
  message: string;
  severity: number;
  createdAt: string;
}

export interface AlertStatusChangedEvent {
  id: string;
  printerId: string;
  status: string; // Enum as string
  acknowledgedAt?: string | null;
  acknowledgedBy?: string | null;
  resolvedAt?: string | null;
  resolvedBy?: string | null;
  dismissedAt?: string | null;
  dismissedBy?: string | null;
  dismissalReason?: string | null;
}

export interface MaintenanceCompletedEvent {
  logId: string;
  printerId: string;
  scheduleId?: string | null;
  performedAt: string;
  performedBy?: string | null;
}

// ============================================================================
// Hierarchical Maintenance Plan Types (V3 architecture)
// Task (global catalog) → Plan (curated task bundle via PlanTask) → Schedule (deployment)
// ============================================================================

/**
 * A global maintenance task in the catalog.
 * Tasks exist independently and can be reused across multiple plans.
 */
export interface MaintenanceTaskDto {
  id: string;
  taskName: string;
  description?: string | null;
  category: string;
  intervalHours?: number | null;
  intervalDays?: number | null;
  estimatedDurationMinutes?: number | null;
  priority: number;
  isActive: boolean;
  isDefault: boolean;
  // Scope rules — nullable booleans indicating which printer features require this task
  requiresEnclosure?: boolean | null;
  requiresCarbonFilter?: boolean | null;
  requiresHepaFilter?: boolean | null;
  requiresBowdenTube?: boolean | null;
  requiresPtfeLiner?: boolean | null;
  requiresLinearRails?: boolean | null;
  requiresLeadScrews?: boolean | null;
  requiresToolchanger?: boolean | null;
  requiresFilamentCutter?: boolean | null;
  requiresHeatedChamber?: boolean | null;
  requiresHeatedBed?: boolean | null;
  requiresMultiMaterial?: boolean | null;
  createdAt: string;
  updatedAt: string;
  taskComponents: MaintenanceTaskComponentDto[];
}

/**
 * Join entity linking a task to a plan, with optional sort order and interval overrides.
 */
export interface PlanTaskDto {
  id: string;
  maintenancePlanId: string;
  maintenanceTaskId: string;
  sortOrder: number;
  intervalHoursOverride?: number | null;
  intervalDaysOverride?: number | null;
  task: MaintenanceTaskDto;
}

/**
 * A maintenance plan groups related tasks for a printer, model, manufacturer, or motion type.
 */
export interface MaintenancePlanDto {
  id: string;
  name: string;
  description?: string | null;
  printerId?: string | null;
  printerName?: string | null;
  printerModelId?: string | null;
  printerModelName?: string | null;
  manufacturerId?: string | null;
  manufacturerName?: string | null;
  motionType?: number | null;
  isActive: boolean;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
  planTasks: PlanTaskDto[];
}

/**
 * Junction linking a task to a component with quantity.
 */
export interface MaintenanceTaskComponentDto {
  id: string;
  maintenanceTaskId: string;
  maintenanceComponentId: string;
  componentName?: string | null;
  quantity: number;
  notes?: string | null;
}

/**
 * A physical component/part in the global inventory.
 */
export interface MaintenanceComponentDto {
  id: string;
  name: string;
  sku?: string | null;
  description?: string | null;
  category: string;
  unitCost?: number | null;
  supplier?: string | null;
  url?: string | null;
  inStock: number;
  minimumStock: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * A maintenance plan deployed to a specific printer.
 */
export interface PrinterMaintenanceScheduleDto {
  id: string;
  maintenancePlanId: string;
  planName: string;
  printerId: string;
  printerName?: string | null;
  isActive: boolean;
  deployedAt: string;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

// ============================================================================
// Request DTOs for hierarchical maintenance plans
// ============================================================================

export interface CreateMaintenancePlanDto {
  name: string;
  description?: string | null;
  printerId?: string | null;
  printerModelId?: string | null;
  manufacturerId?: string | null;
  motionType?: number | null;
  isActive?: boolean;
  isDefault?: boolean;
}

export interface UpdateMaintenancePlanDto {
  name: string;
  description?: string | null;
  printerId?: string | null;
  printerModelId?: string | null;
  manufacturerId?: string | null;
  motionType?: number | null;
  isActive?: boolean;
  isDefault?: boolean;
}

export interface CreateMaintenanceTaskDto {
  taskName: string;
  category: string;
  description?: string | null;
  intervalHours?: number | null;
  intervalDays?: number | null;
  estimatedDurationMinutes?: number | null;
  priority?: number;
  isActive?: boolean;
  isDefault?: boolean;
  requiresEnclosure?: boolean | null;
  requiresCarbonFilter?: boolean | null;
  requiresHepaFilter?: boolean | null;
  requiresBowdenTube?: boolean | null;
  requiresPtfeLiner?: boolean | null;
  requiresLinearRails?: boolean | null;
  requiresLeadScrews?: boolean | null;
  requiresToolchanger?: boolean | null;
  requiresFilamentCutter?: boolean | null;
  requiresHeatedChamber?: boolean | null;
  requiresHeatedBed?: boolean | null;
  requiresMultiMaterial?: boolean | null;
}

export interface UpdateMaintenanceTaskDto {
  taskName: string;
  category: string;
  description?: string | null;
  intervalHours?: number | null;
  intervalDays?: number | null;
  estimatedDurationMinutes?: number | null;
  priority?: number;
  isActive?: boolean;
  isDefault?: boolean;
  requiresEnclosure?: boolean | null;
  requiresCarbonFilter?: boolean | null;
  requiresHepaFilter?: boolean | null;
  requiresBowdenTube?: boolean | null;
  requiresPtfeLiner?: boolean | null;
  requiresLinearRails?: boolean | null;
  requiresLeadScrews?: boolean | null;
  requiresToolchanger?: boolean | null;
  requiresFilamentCutter?: boolean | null;
  requiresHeatedChamber?: boolean | null;
  requiresHeatedBed?: boolean | null;
  requiresMultiMaterial?: boolean | null;
}

export interface AddTaskComponentDto {
  componentId: string;
  quantity?: number;
  notes?: string | null;
}

export interface DeployMaintenancePlanDto {
  maintenancePlanId: string;
  printerId: string;
  notes?: string | null;
}

export interface UpdateScheduleDeploymentDto {
  isActive: boolean;
  notes?: string | null;
}

export interface CreateMaintenanceComponentDto {
  name: string;
  category: string;
  sku?: string | null;
  description?: string | null;
  unitCost?: number | null;
  supplier?: string | null;
  url?: string | null;
  inStock?: number;
  minimumStock?: number;
}

export interface UpdateMaintenanceComponentDto {
  name: string;
  category: string;
  sku?: string | null;
  description?: string | null;
  unitCost?: number | null;
  supplier?: string | null;
  url?: string | null;
  inStock?: number;
  minimumStock?: number;
}
