// Type declaration for runtime debug flags exposed to window.PrintFarmerDebug
// Generated by codemod helpers. Modify per-area flags as needed.

export {};

declare global {
  interface PrintFarmerDebugFlags {
    // Printer UI components
    printerCard?: boolean;
    printerHistory?: boolean;
    printerRealtime?: boolean;
    printerBulkActions?: boolean;
    printerSelection?: boolean;
    printerDashboard?: boolean;
    expandablePrinterCard?: boolean;
    printerDiscoveryModal?: boolean;
    printerDetailsSidebar?: boolean;
    
    // Signal/Communication
    printerSignalR?: boolean;
    // Opt-in only: enables the O(P) lastStatuses snapshot + lastPrinterUpdate
    // exposure in printer-signalr.ts's applyStatusUpdate. Deliberately a
    // separate flag from printerSignalR so enabling it can't self-enable the
    // console.debug gates that read printerSignalR.
    printerSignalRVerbose?: boolean;
    harvestSignalR?: boolean;
    usePrinterStatusUpdates?: boolean;
    
    // Pages and features
    setupWizard?: boolean;
    userManagementPage?: boolean;
    fileBrowser?: boolean;
    telemetrySettingsPage?: boolean;
    
    // Tools and utilities
    toolsCodemodTest?: boolean;
    main?: boolean;
    
    // Add others as you adopt them
    [key: string]: boolean | undefined;
  }

  interface Window {
    PrintFarmerDebug?: PrintFarmerDebugFlags;
  }
}
