// Type declaration for runtime debug flags exposed to window.PrintFarmerDebug
// Generated by codemod helpers. Modify per-area flags as needed.

export {};

declare global {
  interface PrintFarmerDebugFlags {
    // Add per-area flags (optional). Examples:
    printerSignalR?: boolean;
    harvestSignalR?: boolean;
    setupWizard?: boolean;
    userManagementPage?: boolean;
    fileBrowser?: boolean;
    toolsCodemodTest?: boolean;
    main?: boolean;
    // Add others as you adopt them
    [key: string]: boolean | undefined;
  }

  interface Window {
    PrintFarmerDebug?: PrintFarmerDebugFlags;
  }
}
