namespace Farm.Infrastructure.Domain;

// ===========================================================================
// Core Domain Enumerations
// ===========================================================================
// This file consolidates small, standalone enumerations used across the domain.
// Grouped by functional area for easier navigation.
// ===========================================================================
#region G-code and File Management

/// <summary>
/// Indicates the origin of a G-code file in the system.
/// </summary>
public enum GcodeSource
{
    /// <summary>Manually uploaded by a user through the UI or API.</summary>
    Upload = 0,

    /// <summary>Automatically harvested from a connected printer.</summary>
    Harvested = 1,

    /// <summary>Generated by the system (e.g., from slicing). Reserved for future use.</summary>
    Generated = 2
}

/// <summary>
/// Represents the format of a 3D model file.
/// </summary>
public enum ModelFileFormat
{
    /// <summary>STereoLithography format - widely supported mesh format.</summary>
    STL = 0,

    /// <summary>3D Manufacturing Format - supports colors, materials, and metadata.</summary>
    TMF = 1,

    /// <summary>Wavefront OBJ format - text-based geometry format.</summary>
    OBJ = 2,

    /// <summary>Polygon File Format - supports point clouds and meshes.</summary>
    PLY = 3,

    /// <summary>STEP format - CAD interchange format for solid models.</summary>
    STEP = 4
}

/// <summary>
/// Classification for file health audit operations.
/// </summary>
public enum FileAuditType
{
    /// <summary>Audit only 3D model files.</summary>
    Model3D = 0,

    /// <summary>Audit only G-code files.</summary>
    GcodeFile = 1,

    /// <summary>Scan for orphaned files not tracked in the database.</summary>
    OrphanedFiles = 2,

    /// <summary>Perform a complete audit of all file types.</summary>
    FullAudit = 3
}

/// <summary>
/// Health status of a stored file on disk.
/// </summary>
public enum FileHealthStatus
{
    /// <summary>File has never been checked or status is unknown.</summary>
    Unknown = 0,

    /// <summary>File exists and integrity verification passed (hash and size match).</summary>
    Healthy = 1,

    /// <summary>File was not found at the expected storage location.</summary>
    Missing = 2,

    /// <summary>File exists but integrity check failed (hash or size mismatch).</summary>
    Corrupted = 3,

    /// <summary>File exists but cannot be read due to permission or access issues.</summary>
    Inaccessible = 4
}

#endregion

#region Slicing and Profiles

/// <summary>
/// Supported slicer engine types for G-code generation.
/// </summary>
public enum SlicerType
{
    /// <summary>Prusa Research's PrusaSlicer.</summary>
    PrusaSlicer = 0,

    /// <summary>OrcaSlicer - Bambu Lab's fork with advanced features.</summary>
    OrcaSlicer = 1,

    /// <summary>Ultimaker Cura slicer.</summary>
    Cura = 2,

    /// <summary>SuperSlicer - community fork of PrusaSlicer.</summary>
    SuperSlicer = 3
}

/// <summary>
/// Print quality presets affecting layer height and detail level.
/// </summary>
public enum ProfileQuality
{
    /// <summary>Fast printing with lower detail - suitable for prototypes.</summary>
    Draft = 0,

    /// <summary>Balanced speed and quality - suitable for most prints.</summary>
    Standard = 1,

    /// <summary>High detail with slower print speeds - for display models.</summary>
    Fine = 2
}

#endregion

#region Error Handling

/// <summary>
/// Error category classification for retry logic and failure handling.
/// </summary>
public enum ErrorCategory
{
    /// <summary>
    /// Unknown error category requiring manual investigation.
    /// Default value for unclassified errors.
    /// </summary>
    Unknown = 0,

    /// <summary>
    /// Transient errors that may succeed on retry.
    /// Examples: network timeouts, printer temporarily offline, temporary resource contention.
    /// </summary>
    Recoverable = 1,

    /// <summary>
    /// Permanent errors that will not succeed on retry.
    /// Examples: invalid G-code file, unsupported printer model, hardware failure.
    /// </summary>
    Permanent = 2
}

#endregion
