namespace Farm.Infrastructure.Domain;

// ===========================================================================
// Core Domain Enumerations
// ===========================================================================
// This file consolidates small, standalone enumerations used across the domain.
// Grouped by functional area for easier navigation.
// ===========================================================================
#region G-code and File Management

/// <summary>
/// Indicates the origin of a G-code file in the system.
/// </summary>
public enum GcodeSource
{
    /// <summary>Manually uploaded by a user through the UI or API.</summary>
    Upload = 0,

    /// <summary>Automatically harvested from a connected printer.</summary>
    Harvested = 1,

    /// <summary>Generated by the system (e.g., from slicing). Reserved for future use.</summary>
    Generated = 2
}

/// <summary>
/// Classification for file health audit operations.
/// </summary>
public enum FileAuditType
{
    /// <summary>Audit only 3D model files.</summary>
    Model3D = 0,

    /// <summary>Audit only G-code files.</summary>
    GcodeFile = 1,

    /// <summary>Scan for orphaned files not tracked in the database.</summary>
    OrphanedFiles = 2,

    /// <summary>Perform a complete audit of all file types.</summary>
    FullAudit = 3
}

#endregion

#region Slicing and Profiles

// NOTE: ModelFileFormat, SlicerType, ProfileQuality, and FileHealthStatus have been
// migrated to Farm.Slicer.Module.Domain.SlicerEnums. Infra now references
// Farm.Slicer.Module directly; use Farm.Slicer.Module.Domain for these enums.
#endregion

#region Error Handling

/// <summary>
/// Error category classification for retry logic and failure handling.
/// </summary>
public enum ErrorCategory
{
    /// <summary>
    /// Unknown error category requiring manual investigation.
    /// Default value for unclassified errors.
    /// </summary>
    Unknown = 0,

    /// <summary>
    /// Transient errors that may succeed on retry.
    /// Examples: network timeouts, printer temporarily offline, temporary resource contention.
    /// </summary>
    Recoverable = 1,

    /// <summary>
    /// Permanent errors that will not succeed on retry.
    /// Examples: invalid G-code file, unsupported printer model, hardware failure.
    /// </summary>
    Permanent = 2
}

#endregion
