using System.ComponentModel.DataAnnotations;

namespace Farm.Infrastructure.Domain;

/// <summary>
/// Represents an active maintenance alert that requires attention.
/// Generated by the MaintenanceAlertEngine based on printer statistics and maintenance schedules.
/// </summary>
public class MaintenanceAlert
{
    public Guid Id { get; set; }

    /// <summary>
    /// Printer this alert is for
    /// </summary>
    public Guid PrinterId { get; set; }

    /// <summary>
    /// Navigation property to printer
    /// </summary>
    public Printer Printer { get; set; } = null!;

    /// <summary>
    /// Optional: Deployment (printer × plan) that triggered this alert.
    /// Nullable because alerts can outlive a removed deployment.
    /// </summary>
    public Guid? PrinterMaintenanceScheduleId { get; set; }

    /// <summary>
    /// Navigation property to printer maintenance schedule deployment
    /// </summary>
    public PrinterMaintenanceSchedule? PrinterMaintenanceSchedule { get; set; }

    /// <summary>
    /// Optional: The maintenance task that triggered this alert
    /// </summary>
    public Guid? MaintenanceTaskId { get; set; }

    /// <summary>
    /// Navigation property to maintenance task
    /// </summary>
    public MaintenanceTask? MaintenanceTask { get; set; }

    /// <summary>
    /// Alert title/summary
    /// </summary>
    [MaxLength(128)]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed alert message
    /// </summary>
    [MaxLength(512)]
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Severity level (1=Low, 2=Medium, 3=High, 4=Critical)
    /// </summary>
    public int Severity { get; set; } = 2;

    /// <summary>
    /// Alert status
    /// </summary>
    public MaintenanceAlertStatus Status { get; set; } = MaintenanceAlertStatus.Active;

    /// <summary>
    /// Printer hours when alert was triggered
    /// </summary>
    public double PrinterHoursAtTrigger { get; set; }

    /// <summary>
    /// Hours since last maintenance (if applicable)
    /// </summary>
    public double? HoursSinceLastMaintenance { get; set; }

    /// <summary>
    /// Days since last maintenance (if applicable)
    /// </summary>
    public int? DaysSinceLastMaintenance { get; set; }

    /// <summary>
    /// When the alert was created
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When the alert was acknowledged by a user
    /// </summary>
    public DateTime? AcknowledgedAt { get; set; }

    /// <summary>
    /// User who acknowledged the alert
    /// </summary>
    [MaxLength(128)]
    public string? AcknowledgedBy { get; set; }

    /// <summary>
    /// When the alert was resolved (maintenance completed)
    /// </summary>
    public DateTime? ResolvedAt { get; set; }

    /// <summary>
    /// User who resolved the alert
    /// </summary>
    [MaxLength(128)]
    public string? ResolvedBy { get; set; }

    /// <summary>
    /// When the alert was dismissed without maintenance
    /// </summary>
    public DateTime? DismissedAt { get; set; }

    /// <summary>
    /// User who dismissed the alert
    /// </summary>
    [MaxLength(128)]
    public string? DismissedBy { get; set; }

    /// <summary>
    /// Reason for dismissal
    /// </summary>
    [MaxLength(512)]
    public string? DismissalReason { get; set; }

    /// <summary>
    /// When this record was last updated
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Status of a maintenance alert
/// </summary>
public enum MaintenanceAlertStatus
{
    /// <summary>Alert is active and requires attention</summary>
    Active = 0,

    /// <summary>Alert has been acknowledged but not yet resolved</summary>
    Acknowledged = 1,

    /// <summary>Alert has been resolved (maintenance completed)</summary>
    Resolved = 2,

    /// <summary>Alert was dismissed without maintenance</summary>
    Dismissed = 3
}
