using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using Farm.Infrastructure;
using Farm.Infrastructure.Annotations;

namespace Farm.Infrastructure.Domain;

/// <summary>
/// Generic tag that can be applied to any taggable object (Model3D, GcodeFile, Printer, PrintJob, etc.)
/// </summary>
public class Tag
{
    public Guid Id { get; set; }

    public string Name { get; set; } = string.Empty; // e.g., "functional", "decorative", "PLA", "Red"

    /// <summary>
    /// Tag category for auto-generated tags. Null for user-created tags.
    /// Values: "material", "color", "nozzle"
    /// </summary>
    [MaxLength(32)]
    public string? Category { get; set; }

    /// <summary>
    /// Whether this tag was automatically generated by the auto-tagging system.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    public string? Color { get; set; } // Optional hex color for UI display (e.g., "#FF5733")

    public string? Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}
