// <auto-generated />
using System;
using Farm.Slicer.Module.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farm.Slicer.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(SlicerDbContext))]
    [Migration("20260821151953_AddSliceJobFailureReason")]
    partial class AddSliceJobFailureReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Farm.Slicer.Module.Domain.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CleanupDeletionStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CleanupReservationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CleanupReservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclaredSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PromotedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromotedGcodeFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromotionCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionOperationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionOperationKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PromotionStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobId");

                    b.HasIndex("PromotedGcodeFileId");

                    b.HasIndex("PromotionOperationId");

                    b.HasIndex("PromotionOperationKey")
                        .IsUnique();

                    b.HasIndex("WorkerId");

                    b.HasIndex("JobId", "Kind");

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.FilamentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BedTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompatiblePrinters")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NozzleTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrintSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerDistribution")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlicerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlicerVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("IsSystem");

                    b.HasIndex("Material");

                    b.HasIndex("SlicerType");

                    b.HasIndex("Name", "Material", "SlicerType")
                        .IsUnique();

                    b.ToTable("FilamentProfiles");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.MachineModelProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrinterModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlicerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlicerVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("IsSystem");

                    b.HasIndex("Manufacturer");

                    b.HasIndex("PrinterModelId");

                    b.HasIndex("Name", "SlicerType")
                        .IsUnique();

                    b.ToTable("MachineModelProfiles");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.MachineProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("MachineModelProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrinterModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerDistribution")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlicerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlicerVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("IsSystem");

                    b.HasIndex("MachineModelProfileId");

                    b.HasIndex("Manufacturer");

                    b.HasIndex("PrinterModelId");

                    b.HasIndex("SlicerType");

                    b.HasIndex("Name", "SlicerType")
                        .IsUnique();

                    b.ToTable("MachineProfiles");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.Model3D", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUploadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientUploadId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DimensionX")
                        .HasColumnType("REAL");

                    b.Property<double?>("DimensionY")
                        .HasColumnType("REAL");

                    b.Property<double?>("DimensionZ")
                        .HasColumnType("REAL");

                    b.Property<string>("ExtractedMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileFormat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheckDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastVerificationResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L);

                    b.Property<string>("SourceCreator")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLicense")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TriangleCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileFormat");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("FolderId");

                    b.HasIndex("HealthStatus");

                    b.HasIndex("IsValid");

                    b.HasIndex("LastHealthCheckDate");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("UploadedByUserId", "ClientUploadId")
                        .IsUnique();

                    b.ToTable("Models3D");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.ProcessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdvancedSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompatiblePrinters")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableSupports")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("InfillPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double>("LayerHeight")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double>("PrintSpeed")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("PrinterModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileFormat")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerDistribution")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlicerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlicerVersion")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpecificPrinterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("IsDefault");

                    b.HasIndex("IsPublic");

                    b.HasIndex("IsSystem");

                    b.HasIndex("PrinterModelId");

                    b.HasIndex("SlicerType");

                    b.HasIndex("Name", "SlicerType", "PrinterModelId")
                        .IsUnique();

                    b.ToTable("ProcessProfiles");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.SliceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactIdsCsv")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ArtifactsCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ArtifactsTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CalibrationAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CalibrationOrchestrationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CalibrationProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedPrintTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtruderFilamentProfileNamesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FilamentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilamentProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilamentProfileSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FilamentUsedGrams")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdempotencyScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<string>("LayoutDegradationReason")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LeaseFence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MachineProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineProfileSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Model3DId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelFileTransformsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelFileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelFileUrlsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelTransformJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("NormalizedEngine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PinnedWorkerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrinterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProcessProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessProfileSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredCapabilitiesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultFileUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlicerBinarySha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerContainerDigest")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerDistribution")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlicerEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlicerEngineName")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerEngineVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SlicerProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationOrchestrationId");

                    b.HasIndex("Model3DId");

                    b.HasIndex("PrinterId");

                    b.HasIndex("QueuedAt");

                    b.HasIndex("SlicerProfileId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("Status", "NormalizedEngine")
                        .HasDatabaseName("IX_SliceJobs_Status_NormalizedEngine");

                    b.HasIndex("Status", "Priority", "QueuedAt");

                    b.HasIndex("UserId", "IdempotencyScopeId", "Checksum")
                        .IsUnique()
                        .HasDatabaseName("IX_SliceJobs_Owner_Project_Checksum")
                        .HasFilter("\"Checksum\" IS NOT NULL AND \"IdempotencyScopeId\" <> '00000000-0000-0000-0000-000000000000'");

                    b.HasIndex("UserId", "IdempotencyScopeId", "CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("IX_SliceJobs_Owner_Project_Correlation")
                        .HasFilter("\"CorrelationId\" IS NOT NULL AND \"IdempotencyScopeId\" <> '00000000-0000-0000-0000-000000000000'");

                    b.ToTable("SliceJobs");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.SlicerService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApiKeyRotatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrentJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlicerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("UiManifestUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("SlicerType");

                    b.HasIndex("Status");

                    b.ToTable("SlicerServices");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.SlicerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("JitterPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(15.0);

                    b.Property<string>("PerEngineJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SlicerSettings");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("ArtifactBytesProduced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtifactsProduced")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AverageProcessingTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedJobs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedJobs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OfflineAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OnlineAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeat");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.MachineProfile", b =>
                {
                    b.HasOne("Farm.Slicer.Module.Domain.MachineModelProfile", "MachineModelProfile")
                        .WithMany("MachineProfiles")
                        .HasForeignKey("MachineModelProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MachineModelProfile");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.SliceJob", b =>
                {
                    b.HasOne("Farm.Slicer.Module.Domain.ProcessProfile", "SlicerProfile")
                        .WithMany()
                        .HasForeignKey("SlicerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SlicerProfile");
                });

            modelBuilder.Entity("Farm.Slicer.Module.Domain.MachineModelProfile", b =>
                {
                    b.Navigation("MachineProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
