using Farm.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Farm.Infrastructure.Data.Configurations;

/// <summary>
/// Entity Framework configuration for the Role entity.
/// Extracted from AppDbContext.OnModelCreating for better maintainability.
/// </summary>
public class RoleConfiguration : IEntityTypeConfiguration<Role>
{
    public void Configure(EntityTypeBuilder<Role> builder)
    {
        builder.HasKey(r => r.Id);

        // Basic properties
        builder.Property(r => r.Name).IsRequired().HasMaxLength(50);
        builder.Property(r => r.DisplayName).IsRequired().HasMaxLength(100);
        builder.Property(r => r.Description).HasColumnType("TEXT");

        // Optimistic concurrency token (#1449): every UPDATE generated by EF Core includes
        // "AND UpdatedAt = @original" in its WHERE clause. If a concurrent writer already
        // changed the row, 0 rows are affected and EF throws DbUpdateConcurrencyException
        // (a DbUpdateException) instead of silently overwriting the other writer's change.
        builder.Property(r => r.UpdatedAt).IsConcurrencyToken();

        // Unique constraints and indexes
        builder.HasIndex(r => r.Name).IsUnique();
        builder.HasIndex(r => r.IsSystemRole);
        builder.HasIndex(r => r.IsActive);
    }
}
