using Farm.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Farm.Infrastructure.Data.Configurations;

/// <summary>
/// Entity configuration for Tag - generic tag for organizing objects (3D models, gcode files, etc.)
/// </summary>
public class TagConfiguration : IEntityTypeConfiguration<Tag>
{
    public void Configure(EntityTypeBuilder<Tag> builder)
    {
        _ = builder.HasKey(t => t.Id);

        // Properties
        _ = builder.Property(t => t.Name).IsRequired().HasMaxLength(128);
        _ = builder.Property(t => t.Category).IsRequired().HasMaxLength(32).HasDefaultValue("manual");
        _ = builder.Property(t => t.IsAutoGenerated).HasDefaultValue(false);
        _ = builder.Property(t => t.Color).HasMaxLength(7); // Hex color codes
        _ = builder.Property(t => t.Description).HasMaxLength(512);

        // Unique index on Name+Category to allow same name in different categories
        _ = builder.HasIndex(t => new { t.Name, t.Category })
            .IsUnique()
            .HasDatabaseName("IX_Tags_Name_Category");

        // Index for analytics
        _ = builder.HasIndex(t => t.CreatedAt);

        // Index for finding auto-generated tags by category
        _ = builder.HasIndex(t => new { t.Category, t.IsAutoGenerated })
            .HasDatabaseName("IX_Tags_Category_IsAutoGenerated");
    }
}
