FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["src/printer-discovery/PrinterDiscoveryService.csproj", "src/printer-discovery/"]

RUN dotnet restore "src/printer-discovery/PrinterDiscoveryService.csproj"

COPY . .
WORKDIR "/src/src/printer-discovery"

RUN dotnet build "PrinterDiscoveryService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PrinterDiscoveryService.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

COPY --from=publish /app/publish .

EXPOSE 7080

ENTRYPOINT ["dotnet", "PrinterDiscoveryService.dll"]
