using Farm.OrcaSlicer.Worker.Tests.Support;
using FluentAssertions;
using Xunit;

namespace Farm.OrcaSlicer.Worker.Tests;

/// <summary>
/// Fast, docker-free tests for <see cref="OrcaGcodeOrientationReader"/> — the G-code
/// bounding-box-size reader used by the real-OrcaSlicer-CLI rotation test
/// (<c>PinnedOrcaCliRotationTests</c> in <c>Farm.Web.IntegrationTests</c>, issue #1802) to measure
/// the actual sliced object's orientation from a real OrcaSlicer G-code output.
/// </summary>
public class OrcaGcodeOrientationReaderTests
{
    [Fact]
    public void ComputeExtrusionExtent_TravelOnlyMoves_AreExcludedFromBoundingBox()
    {
        string[] lines =
        [
            "G90",
            "G1 X0 Y0 Z0.2 F1200", // travel, no E
            "G1 X100 Y100 F1200", // travel, no E
            "G1 X1 Y1 E0.5", // first extrusion
            "G1 X2 Y2 E1.0", // extrusion
        ];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeX.Should().BeApproximately(1.0, 1e-9);
        extent.SizeY.Should().BeApproximately(1.0, 1e-9);
    }

    [Fact]
    public void ComputeExtrusionExtent_MeasuresZRangeAcrossLayers()
    {
        string[] lines =
        [
            "G90",
            "G1 Z0.2",
            "G1 X0 Y0 E0.1",
            "G1 Z5.4",
            "G1 X0 Y0 E0.2",
        ];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeZ.Should().BeApproximately(5.2, 1e-9);
    }

    [Fact]
    public void ComputeExtrusionExtent_RelativePositioning_Throws()
    {
        string[] lines = ["G90", "G1 X0 Y0 E0.1", "G91", "G1 X1 Y1 E0.2"];

        Action act = () => OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        act.Should().Throw<InvalidOperationException>();
    }

    [Fact]
    public void ComputeExtrusionExtent_NoExtrusion_Throws()
    {
        string[] lines = ["G90", "G1 X0 Y0", "G1 X10 Y10"];

        Action act = () => OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        act.Should().Throw<InvalidOperationException>();
    }

    [Fact]
    public void ComputeExtrusionExtent_IgnoresCommentsAndBlankLines()
    {
        string[] lines =
        [
            "; generated by OrcaSlicer",
            "",
            "G90",
            "G1 X0 Y0 E0.1 ; move and extrude",
            "G1 X3 Y4 E0.5",
        ];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeX.Should().BeApproximately(3.0, 1e-9);
        extent.SizeY.Should().BeApproximately(4.0, 1e-9);
    }

    [Fact]
    public void ComputeExtrusionExtent_G0MovesCanExtrudeToo()
    {
        string[] lines = ["G90", "G0 X0 Y0 E0.1", "G0 X10 Y0 E0.6"];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeX.Should().BeApproximately(10.0, 1e-9);
        extent.SizeY.Should().BeApproximately(0.0, 1e-9);
    }
}
