using Farm.OrcaSlicer.Worker.Tests.Support;
using FluentAssertions;
using Xunit;

namespace Farm.OrcaSlicer.Worker.Tests;

/// <summary>
/// Fast, docker-free tests for <see cref="OrcaGcodeOrientationReader"/> — the G-code
/// bounding-box-size reader used by the real-OrcaSlicer-CLI rotation test
/// (<c>PinnedOrcaCliRotationTests</c> in <c>Farm.Web.IntegrationTests</c>, issue #1802) to measure
/// the actual sliced object's orientation from a real OrcaSlicer G-code output.
/// </summary>
public class OrcaGcodeOrientationReaderTests
{
    [Fact]
    public void ComputeExtrusionExtent_TravelOnlyMoves_AreExcludedFromBoundingBox()
    {
        string[] lines =
        [
            "G90",
            "G1 X0 Y0 Z0.2 F1200", // travel, no E
            "G1 X100 Y100 F1200", // travel, no E
            "G1 X1 Y1 E0.5", // first extrusion
            "G1 X2 Y2 E1.0", // extrusion
        ];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeX.Should().BeApproximately(1.0, 1e-9);
        extent.SizeY.Should().BeApproximately(1.0, 1e-9);
    }

    [Fact]
    public void ComputeExtrusionExtent_MeasuresZRangeAcrossLayers()
    {
        string[] lines =
        [
            "G90",
            "G1 Z0.2",
            "G1 X0 Y0 E0.1",
            "G1 Z5.4",
            "G1 X0 Y0 E0.2",
        ];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeZ.Should().BeApproximately(5.2, 1e-9);
    }

    [Fact]
    public void ComputeExtrusionExtent_RelativePositioning_Throws()
    {
        string[] lines = ["G90", "G1 X0 Y0 E0.1", "G91", "G1 X1 Y1 E0.2"];

        Action act = () => OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        act.Should().Throw<InvalidOperationException>();
    }

    [Fact]
    public void ComputeExtrusionExtent_NoExtrusion_Throws()
    {
        string[] lines = ["G90", "G1 X0 Y0", "G1 X10 Y10"];

        Action act = () => OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        act.Should().Throw<InvalidOperationException>();
    }

    [Fact]
    public void ComputeExtrusionExtent_IgnoresCommentsAndBlankLines()
    {
        string[] lines =
        [
            "; generated by OrcaSlicer",
            "",
            "G90",
            "G1 X0 Y0 E0.1 ; move and extrude",
            "G1 X3 Y4 E0.5",
        ];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeX.Should().BeApproximately(3.0, 1e-9);
        extent.SizeY.Should().BeApproximately(4.0, 1e-9);
    }

    [Fact]
    public void ComputeExtrusionExtent_G0MovesCanExtrudeToo()
    {
        string[] lines = ["G90", "G0 X0 Y0 E0.1", "G0 X10 Y0 E0.6"];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeX.Should().BeApproximately(10.0, 1e-9);
        extent.SizeY.Should().BeApproximately(0.0, 1e-9);
    }

    [Fact]
    public void ComputeExtrusionExtent_G92ExtruderReset_StillIncludesPostResetExtrusionMoves()
    {
        // Absolute-extrusion G-code commonly resets the E axis mid-print (e.g. "G92 E0" between
        // objects, at a layer change, or after a purge/wipe sequence) purely to avoid unbounded
        // float drift over a long print — it is not a travel move and carries no X/Y/Z motion of
        // its own. A reader that ignores G92 entirely keeps comparing later E values against the
        // stale pre-reset E, so the real printing move right after the reset looks like it is
        // retracting rather than extruding and gets wrongly excluded from the measured bounding
        // box — silently shrinking it and making the result depend on where the profile happens
        // to reset the extruder rather than on the model's own geometry.
        string[] lines =
        [
            "G90",
            "G1 X0 Y0 E5", // first extrusion move, bbox so far: X=[0,0] Y=[0,0]
            "G1 X10 Y0 E10", // second extrusion move, bbox so far: X=[0,10] Y=[0,0]
            "G92 E0", // reset only, no motion — must not be treated as a travel/extrusion move
            "G1 X10 Y20 E2", // real printing move after the reset: must still count as extruding
        ];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeX.Should().BeApproximately(10.0, 1e-9);
        extent.SizeY.Should().BeApproximately(20.0, 1e-9, "the move after G92 E0 must still be measured as extruding");
    }

    [Fact]
    public void ComputeExtrusionExtent_G92WithoutEAxis_DoesNotAffectExtrusionTracking()
    {
        // A bare "G92 X0 Y0" (or similar) re-declares position without touching the extruder axis
        // at all; it must not reset the tracked E baseline, and it must not itself be counted as an
        // extruding move even though it changes the current X/Y.
        string[] lines =
        [
            "G90",
            "G1 X0 Y0 E1",
            "G92 X0 Y0", // position redeclaration only, no E — must be a no-op for extrusion tracking
            "G1 X5 Y0 E2", // still extruding relative to the pre-G92 E baseline
        ];

        GcodeExtent extent = OrcaGcodeOrientationReader.ComputeExtrusionExtent(lines);

        extent.SizeX.Should().BeApproximately(5.0, 1e-9);
    }
}
