// <auto-generated />
using System;
using Farm.Web.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Farm.Web.Api.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250901030849_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Farm.Web.Api.Domain.DiscoveredGcodeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlreadyInLibrary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExistingLibraryFileId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExtractedFilamentLength")
                        .HasColumnType("REAL");

                    b.Property<string>("ExtractedInfill")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedLayerHeight")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedMaterial")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExtractedNozzleDiameter")
                        .HasColumnType("REAL");

                    b.Property<double?>("ExtractedPrintTime")
                        .HasColumnType("REAL");

                    b.Property<string>("ExtractedSlicerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedSlicerVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HarvestOperationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProcessingFailed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlreadyInLibrary");

                    b.HasIndex("FileHash");

                    b.HasIndex("HarvestOperationId");

                    b.HasIndex("IsSelected");

                    b.ToTable("DiscoveredGcodeFiles");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.GcodeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("BedTemperature")
                        .HasColumnType("REAL");

                    b.Property<string>("CompatibleMaterials")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedFilamentLengthMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("EstimatedFilamentWeightG")
                        .HasColumnType("REAL");

                    b.Property<double?>("EstimatedPrintTimeMinutes")
                        .HasColumnType("REAL");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("InfillPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastSeenOnPrinter")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LayerHeight")
                        .HasColumnType("REAL");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalPrinterPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PrintSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("PrintTemperatures")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RequiredBuildVolumeX")
                        .HasColumnType("REAL");

                    b.Property<double?>("RequiredBuildVolumeY")
                        .HasColumnType("REAL");

                    b.Property<double?>("RequiredBuildVolumeZ")
                        .HasColumnType("REAL");

                    b.Property<string>("RequiredMaterial")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("RequiredNozzleDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("SlicerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlicerVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourcePrinterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetPrinterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPrinterModels")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("RequiredMaterial");

                    b.HasIndex("RequiredNozzleDiameter");

                    b.HasIndex("SourcePrinterId");

                    b.HasIndex("TargetModelId");

                    b.HasIndex("TargetPrinterId");

                    b.HasIndex("UploadedAt");

                    b.ToTable("GcodeFiles");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.GcodeHarvestOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesErrored")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSubdirectories")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAfter")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytesProcessed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("GcodeHarvestOperations");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ActualFilamentUsage")
                        .HasColumnType("REAL");

                    b.Property<long?>("ActualPrintTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedPrinterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedFilamentUsage")
                        .HasColumnType("REAL");

                    b.Property<long?>("EstimatedPrintTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludedPrinterIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GcodeFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredPrinterIds")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("QueuePosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredCapabilities")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredMaterialType")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RequiredNozzleDiameter")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedPrinterId");

                    b.HasIndex("GcodeFileId");

                    b.HasIndex("Priority");

                    b.HasIndex("QueuedAt");

                    b.HasIndex("Status");

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("Backend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DateAcquired")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalServerUrl")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ModelId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.PrinterCapabilities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentMaterial")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentSpoolId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEnclosure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHeatedBed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxBedTemp")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxBuildVolumeX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxBuildVolumeY")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxBuildVolumeZ")
                        .HasColumnType("REAL");

                    b.Property<int?>("MaxHotendTemp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxPrintSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinBedTemp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinHotendTemp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MultiMaterial")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NozzleDiameter")
                        .HasColumnType("REAL");

                    b.Property<int>("NumberOfExtruders")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedMaterials")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsAutoLeveling")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("NozzleDiameter");

                    b.HasIndex("PrinterId")
                        .IsUnique();

                    b.ToTable("PrinterCapabilities");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.PrinterModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultBackend")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxX")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxY")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxZ")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId", "Name")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.Spool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedPrinterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InUse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AssignedPrinterId");

                    b.ToTable("Spools");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.SpoolmanConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpoolmanConfigs");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.DiscoveredGcodeFile", b =>
                {
                    b.HasOne("Farm.Web.Api.Domain.GcodeHarvestOperation", "HarvestOperation")
                        .WithMany()
                        .HasForeignKey("HarvestOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HarvestOperation");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.GcodeFile", b =>
                {
                    b.HasOne("Farm.Web.Api.Domain.Printer", "SourcePrinter")
                        .WithMany()
                        .HasForeignKey("SourcePrinterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Farm.Web.Api.Domain.PrinterModel", "TargetModel")
                        .WithMany()
                        .HasForeignKey("TargetModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Farm.Web.Api.Domain.Printer", "TargetPrinter")
                        .WithMany()
                        .HasForeignKey("TargetPrinterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SourcePrinter");

                    b.Navigation("TargetModel");

                    b.Navigation("TargetPrinter");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.GcodeHarvestOperation", b =>
                {
                    b.HasOne("Farm.Web.Api.Domain.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.PrintJob", b =>
                {
                    b.HasOne("Farm.Web.Api.Domain.Printer", "AssignedPrinter")
                        .WithMany()
                        .HasForeignKey("AssignedPrinterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Farm.Web.Api.Domain.GcodeFile", "GcodeFile")
                        .WithMany()
                        .HasForeignKey("GcodeFileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedPrinter");

                    b.Navigation("GcodeFile");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.Printer", b =>
                {
                    b.HasOne("Farm.Web.Api.Domain.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Farm.Web.Api.Domain.PrinterModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manufacturer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.PrinterCapabilities", b =>
                {
                    b.HasOne("Farm.Web.Api.Domain.Printer", "Printer")
                        .WithOne("Capabilities")
                        .HasForeignKey("Farm.Web.Api.Domain.PrinterCapabilities", "PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.PrinterModel", b =>
                {
                    b.HasOne("Farm.Web.Api.Domain.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.Spool", b =>
                {
                    b.HasOne("Farm.Web.Api.Domain.Printer", null)
                        .WithMany()
                        .HasForeignKey("AssignedPrinterId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Farm.Web.Api.Domain.Printer", b =>
                {
                    b.Navigation("Capabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
