// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1118:Parameter should not span multiple lines", Justification = "Complex JSON structure requires multi-line formatting for readability", Scope = "member", Target = "~M:Farm.Infrastructure.Services.Gcode.HarvestErrorHelper.CreateErrorDetailsJson(System.Exception,System.String)~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1407:Arithmetic expressions should declare precedence", Justification = "Standard arithmetic operators follow well-understood precedence rules", Scope = "member", Target = "~M:Farm.Infrastructure.Services.Gcode.GcodeHarvestService.ExtractMetadataFromLine(System.String,Farm.Infrastructure.GcodeMetadataDto)~Farm.Infrastructure.GcodeMetadataDto")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1407:Arithmetic expressions should declare precedence", Justification = "Standard arithmetic operators follow well-understood precedence rules", Scope = "member", Target = "~M:Farm.Infrastructure.Services.Models.ModelAnalysisService.AnalyzeStlAsync(System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Farm.Infrastructure.Services.Models.ModelAnalysisResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1407:Arithmetic expressions should declare precedence", Justification = "Matrix transformation math follows standard precedence", Scope = "member", Target = "~M:Farm.Infrastructure.Services.Models.ThreeMfToStlConversionService.ApplyTransform(System.Collections.Generic.List{System.ValueTuple{System.Single,System.Single,System.Single}},System.String)~System.Collections.Generic.List{System.ValueTuple{System.Single,System.Single,System.Single}}")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1407:Arithmetic expressions should declare precedence", Justification = "STL binary format generation follows standard precedence", Scope = "member", Target = "~M:Farm.Infrastructure.Services.Models.ThreeMfToStlConversionService.GenerateBinarySTL(System.Collections.Generic.List{System.ValueTuple{System.Single,System.Single,System.Single}},System.Collections.Generic.List{System.ValueTuple{System.Int32,System.Int32,System.Int32}})~System.Byte[]")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1407:Arithmetic expressions should declare precedence", Justification = "Statistical calculations follow standard precedence", Scope = "member", Target = "~M:Farm.Infrastructure.Services.PredictionService.GetDurationStatsAsync(System.Nullable{System.Guid},System.String,System.Nullable{System.DateTime},System.Nullable{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Farm.Infrastructure.Services.PredictionDurationStatsDto}")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1407:Arithmetic expressions should declare precedence", Justification = "Statistical calculations follow standard precedence", Scope = "member", Target = "~M:Farm.Infrastructure.Services.PredictionService.GetMaterialStatsAsync(System.Nullable{System.Guid},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Collections.Generic.Dictionary{System.String,Farm.Infrastructure.Services.PredictionDurationStatsDto}}")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1311:Static readonly fields should begin with upper-case letter", Justification = "Array constant follows existing codebase naming convention", Scope = "member", Target = "~F:Farm.Infrastructure.Services.Gcode.GcodeHarvestService.sourceArray")]
