using System.IdentityModel.Tokens.Jwt;
using System.Net;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Farm.Infrastructure;
using Farm.Infrastructure.Data;
using Farm.Infrastructure.Domain;
using Farm.Infrastructure.Dtos;
using Farm.Infrastructure.Repositories.Api;
using Farm.Infrastructure.Repositories.Users;
using Farm.Infrastructure.Security;
using Farm.Infrastructure.Services.Interfaces;
using Farm.Infrastructure.Services.Queue;
using Farm.Infrastructure.Services.Quota;
using Farm.Infrastructure.Services.RateLimiting;
using Farm.Infrastructure.Settings;
using Farm.Modules.Devices.Services.OctoPrint;
using Farm.Modules.Gcode.DTOs;
using Farm.Modules.Gcode.Services.Gcode;
using Farm.Modules.Identity.Services.Admin;
using Farm.Web.Api.Controllers;
using Farm.Web.Api.Startup;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.IdentityModel.Tokens;
using Moq;

namespace Farm.Web.Api.Tests.Security;

/// <summary>
/// Exercises the production authentication middleware, policy, and multipart controller with
/// isolated storage/queue boundaries. Database-backed resource ACL coverage lives alongside
/// this suite in <see cref="OctoPrintUploadAuthorizationTests"/>.
/// </summary>
public sealed class OctoPrintOptionalAuthenticationTests : IAsyncLifetime
{
    private const string ApiKeyValue = "octoprint-upload-test-key";
    private const string GlobalApiKeyValue = "octoprint-global-test-key";
    private const string SigningKey = "octoprint-upload-test-signing-key-not-for-production";
    private const string Gcode = "; generated by OrcaSlicer\nG28\nG1 X0 Y0 Z0.2 F1200\n";
    private readonly Guid _userId = Guid.NewGuid();
    private readonly Guid _printerId = Guid.NewGuid();
    private readonly Guid _fileId = Guid.NewGuid();
    private readonly Guid _jobId = Guid.NewGuid();
    private readonly Mock<IApiKeyRepository> _apiKeys = new();
    private readonly Mock<IUsersRepository> _users = new();
    private readonly Mock<IGcodeFilesService> _files = new(MockBehavior.Strict);
    private readonly Mock<IJobQueueService> _queue = new(MockBehavior.Strict);
    private readonly Mock<IRateLimitService> _rateLimits = new();
    private readonly IHost _host;
    private HttpClient _client = null!;
    private OctoPrintSettings _settings = new();
    private string? _uploadedContent;

    public OctoPrintOptionalAuthenticationTests()
    {
        var settingsService = new Mock<ISettingsService>();
        settingsService.Setup(service => service.Get<OctoPrintSettings>()).Returns(() => _settings);
        _users.Setup(repository => repository.GetUserEntityAsync(_userId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new User { Id = _userId, Username = "slicer-user", IsActive = true });
        _users.Setup(repository => repository.GetActiveRoleNamesAsync(_userId, It.IsAny<CancellationToken>()))
            .ReturnsAsync([]);
        _users.Setup(repository => repository.GetGrantedPermissionsAsync(_userId, It.IsAny<CancellationToken>()))
            .ReturnsAsync([("queue", "write")]);
        _users.Setup(repository => repository.GetDeniedPermissionsAsync(_userId, It.IsAny<CancellationToken>()))
            .ReturnsAsync([]);
        _rateLimits.Setup(service => service.CheckOctoPrintUploadLimitAsync(
                It.IsAny<string>(), It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new RateLimitResult(true, 59));
        _files.Setup(service => service.UploadFileAsync(
                null, It.IsAny<IFormFile>(), It.IsAny<IGcodeUploadSettings>(),
                It.IsAny<IGcodeUploadQuotaService>(), It.IsAny<CancellationToken>()))
            .Returns(async (string? _, IFormFile file, IGcodeUploadSettings _, IGcodeUploadQuotaService _, CancellationToken ct) =>
            {
                using var reader = new StreamReader(file.OpenReadStream());
                _uploadedContent = await reader.ReadToEndAsync(ct);
                return new GcodeFileEntryDto(
                    $"{_fileId}.gcode", file.FileName, file.Length, DateTime.UtcNow, false,
                    Id: _fileId.ToString(), RequiredMaterial: "PLA",
                    ExtractedNozzleDiameter: 0.4, ExtractedPrinterModel: "Qidi Plus 4");
            });
        _queue.Setup(service => service.AddJobToQueueAsync(
                It.IsAny<QueuePrintJobDto>(), It.IsAny<Guid?>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new JobQueuePrintJobDto
            {
                Id = _jobId,
                GcodeFileId = _fileId,
                AssignedPrinterId = _printerId,
                AssignedPrinterName = "Test Qidi Plus 4",
            });

        _host = new HostBuilder().ConfigureWebHost(builder => builder
            .UseTestServer()
            .UseEnvironment("Testing")
            .ConfigureAppConfiguration((_, configuration) => configuration.AddInMemoryCollection(
                new Dictionary<string, string?>
                {
                    ["Jwt:Key"] = SigningKey,
                    ["OctoPrint:GlobalApiKey"] = GlobalApiKeyValue,
                }))
            .ConfigureServices((context, services) =>
            {
                services.AddPrintFarmerAuthentication(context.Configuration, context.HostingEnvironment);
                services.AddSingleton(settingsService.Object);
                services.AddSingleton(_apiKeys.Object);
                services.AddSingleton(_users.Object);
                services.AddScoped<IOctoPrintAuthService, OctoPrintAuthService>();
                services.AddSingleton(_files.Object);
                services.AddSingleton(_queue.Object);
                services.AddSingleton(_rateLimits.Object);
                services.AddSingleton(Mock.Of<IGcodeUploadSettings>());
                services.AddSingleton(Mock.Of<IGcodeUploadQuotaService>());
                // Deliberately stale options: authentication must use live ISettingsService values.
                services.Configure<OctoPrintSettings>(settings => settings.RequireApiKey = true);
                services.AddControllers().AddApplicationPart(typeof(OctoPrintCompatController).Assembly);
            })
            .Configure(app =>
            {
                app.UseRouting();
                app.UseAuthentication();
                app.UseAuthorization();
                app.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();
                    endpoints.MapGet("/protected", context => context.Response.WriteAsync("protected"));
                });
            })).Build();
    }

    public async Task InitializeAsync()
    {
        await _host.StartAsync();
        _client = _host.GetTestClient();
    }

    [Fact]
    public async Task Upload_CatalogMetadata_ListsActualRouteAndStillAllowsAnonymousEnqueue()
    {
        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.Accepted, response.StatusCode);
        VerifyQueuedActor(null);

        DbContextOptions<AppDbContext> options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase($"octoprint-permission-catalog-{Guid.NewGuid()}")
            .Options;
        await using var db = new AppDbContext(options);
        var catalogService = new PermissionCatalogService(
            _host.Services.GetRequiredService<EndpointDataSource>(), db);

        PermissionCatalogDto catalog = await catalogService.GetCatalogAsync();

        PermissionResourceGroupDto group = Assert.Single(catalog.Resources, group => group.Resource == "queue");
        PermissionCatalogEntryDto entry = Assert.Single(
            group.Permissions, permission => permission.Permission == PrintFarmerPermissions.Queue.Write);
        Assert.Single(entry.Routes, route => route.Method == "POST" && route.Template == "api/files/local");
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Upload_OptionalWithoutCredentials_ReturnsFileAndEnqueuesOnlyWhenRequested(bool print)
    {
        using HttpResponseMessage response = await UploadAsync(print);

        Assert.Equal(print ? HttpStatusCode.Accepted : HttpStatusCode.OK, response.StatusCode);
        using JsonDocument body = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
        Assert.Equal(_fileId.ToString(), body.RootElement.GetProperty("file").GetProperty("id").GetString());
        Assert.Equal("upload.gcode", body.RootElement.GetProperty("file").GetProperty("fileName").GetString());
        Assert.Equal(Encoding.UTF8.GetByteCount(Gcode), body.RootElement.GetProperty("file").GetProperty("fileSize").GetInt64());
        Assert.Equal(Gcode, _uploadedContent);
        Assert.Single(_files.Invocations);

        if (print)
        {
            Assert.Equal(_jobId, body.RootElement.GetProperty("jobId").GetGuid());
            Assert.Equal("Queued", body.RootElement.GetProperty("status").GetString());
            Assert.Equal("Test Qidi Plus 4", body.RootElement.GetProperty("assignedPrinter").GetString());
            VerifyQueuedActor(null);
        }
        else
        {
            Assert.False(body.RootElement.TryGetProperty("jobId", out _));
            Assert.Empty(_queue.Invocations);
        }
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Upload_RequiredWithoutCredentials_RejectsBeforeSaving(bool print)
    {
        _settings = new OctoPrintSettings { RequireApiKey = true };

        using HttpResponseMessage response = await UploadAsync(print);

        await AssertAuthenticationRejectedAsync(response);
    }

    [Theory]
    [InlineData(false, "invalid")]
    [InlineData(true, "invalid")]
    [InlineData(false, "desktop")]
    [InlineData(true, "desktop")]
    [InlineData(false, "expired")]
    [InlineData(true, "expired")]
    [InlineData(false, "ownerless")]
    [InlineData(true, "ownerless")]
    [InlineData(false, "inactive-owner")]
    [InlineData(true, "inactive-owner")]
    [InlineData(false, "missing-owner")]
    [InlineData(true, "missing-owner")]
    [InlineData(false, "global")]
    [InlineData(true, "global")]
    public async Task Upload_UnusableApiKey_RejectsBeforeSaving(bool requireApiKey, string reason)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        ApiKey key = SeedApiKey();
        switch (reason)
        {
            case "invalid":
                _apiKeys.Reset();
                break;
            case "desktop":
                key.Purpose = ApiKeyPurpose.Desktop;
                break;
            case "expired":
                key.ExpiresAt = DateTime.UtcNow.AddMinutes(-1);
                break;
            case "ownerless":
                key.UserId = null;
                break;
            case "inactive-owner":
                _users.Setup(repository => repository.GetUserEntityAsync(_userId, It.IsAny<CancellationToken>()))
                    .ReturnsAsync(new User { Id = _userId, IsActive = false });
                break;
            case "missing-owner":
                _users.Setup(repository => repository.GetUserEntityAsync(_userId, It.IsAny<CancellationToken>()))
                    .ReturnsAsync((User?)null);
                break;
        }

        _client.DefaultRequestHeaders.Add("X-Api-Key", reason == "global" ? GlobalApiKeyValue : ApiKeyValue);

        using HttpResponseMessage response = await UploadAsync();

        await AssertAuthenticationRejectedAsync(response);
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Upload_ValidBearerWithInvalidApiKey_RejectsBeforeSaving(bool requireApiKey)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        SetBearer(_userId.ToString());
        _client.DefaultRequestHeaders.Add("X-Api-Key", "invalid-key");

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        AssertNoSideEffects();
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Upload_ValidApiKeyWithInvalidBearer_RejectsBeforeSaving(bool requireApiKey)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        SeedApiKey();
        _client.DefaultRequestHeaders.Add("X-Api-Key", ApiKeyValue);
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", "invalid-token");

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        AssertNoSideEffects();
    }

    [Theory]
    [InlineData(false, false)]
    [InlineData(true, false)]
    [InlineData(false, true)]
    [InlineData(true, true)]
    public async Task Upload_ValidOctoPrintKey_PreservesUserActor(bool requireApiKey, bool rawKey)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        SeedApiKey(rawKey);
        _client.DefaultRequestHeaders.Add("X-Api-Key", ApiKeyValue);

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.Accepted, response.StatusCode);
        VerifyQueuedActor(_userId);
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Upload_ValidBearer_PreservesUserActor(bool requireApiKey)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        SetBearer(_userId.ToString());

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.Accepted, response.StatusCode);
        VerifyQueuedActor(_userId);
    }

    [Theory]
    [InlineData(false, false)]
    [InlineData(true, false)]
    [InlineData(false, true)]
    [InlineData(true, true)]
    public async Task Upload_AuthenticatedWithoutQueuePermission_RejectsBeforeSaving(bool requireApiKey, bool bearer)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        if (bearer)
        {
            SetBearer(_userId.ToString(), grantQueuePermission: false);
        }
        else
        {
            SeedApiKey();
            _client.DefaultRequestHeaders.Add("X-Api-Key", ApiKeyValue);
            _users.Setup(repository => repository.GetGrantedPermissionsAsync(_userId, It.IsAny<CancellationToken>()))
                .ReturnsAsync([]);
        }

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        AssertNoSideEffects();
    }

    [Theory]
    [InlineData(false, false)]
    [InlineData(true, false)]
    [InlineData(false, true)]
    [InlineData(true, true)]
    public async Task Upload_AuthenticatedResourceDenied_PreservesForbiddenResult(bool requireApiKey, bool groupDenied)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        SeedApiKey();
        _client.DefaultRequestHeaders.Add("X-Api-Key", ApiKeyValue);
        Exception denial = groupDenied
            ? new QueueGroupAccessDeniedException(Guid.NewGuid(), _userId)
            : new UnauthorizedAccessException("Printer access denied");
        _queue.Setup(service => service.AddJobToQueueAsync(
                It.IsAny<QueuePrintJobDto>(), _userId, It.IsAny<CancellationToken>()))
            .ThrowsAsync(denial);

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        VerifyQueuedActor(_userId);
        _queue.Verify(service => service.AddJobToQueueAsync(
            It.IsAny<QueuePrintJobDto>(), null, It.IsAny<CancellationToken>()), Times.Never);
    }

    [Theory]
    [InlineData(false, null)]
    [InlineData(true, null)]
    [InlineData(false, "not-a-guid")]
    [InlineData(true, "not-a-guid")]
    public async Task Upload_MalformedAuthenticatedIdentity_RejectsBeforeSaving(bool requireApiKey, string? subject)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        SetBearer(subject);

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        AssertNoSideEffects();
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Upload_InvalidBearer_DoesNotFallBackToAnonymous(bool requireApiKey)
    {
        _settings = new OctoPrintSettings { RequireApiKey = requireApiKey };
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", "invalid-token");

        using HttpResponseMessage response = await UploadAsync();

        await AssertAuthenticationRejectedAsync(response);
    }

    [Fact]
    public async Task Upload_RuntimeSettingChanged_AppliesToNextRequest()
    {
        using HttpResponseMessage optional = await UploadAsync();
        Assert.Equal(HttpStatusCode.Accepted, optional.StatusCode);

        _settings = new OctoPrintSettings { RequireApiKey = true };
        using HttpResponseMessage required = await UploadAsync();
        Assert.Equal(HttpStatusCode.Unauthorized, required.StatusCode);
        Assert.Single(_files.Invocations);
        Assert.Single(_queue.Invocations);

        _settings = new OctoPrintSettings { RequireApiKey = false };
        using HttpResponseMessage optionalAgain = await UploadAsync();
        Assert.Equal(HttpStatusCode.Accepted, optionalAgain.StatusCode);
        Assert.Equal(2, _files.Invocations.Count);
        Assert.Equal(2, _queue.Invocations.Count);
    }

    [Theory]
    [InlineData("/api/version")]
    [InlineData("/api/server")]
    public async Task Probe_RuntimeSettingChanged_PreservesAnonymousAndGlobalKeySemantics(string path)
    {
        using HttpResponseMessage optional = await _client.GetAsync(path);
        Assert.Equal(HttpStatusCode.OK, optional.StatusCode);

        _settings = new OctoPrintSettings { RequireApiKey = true };
        using HttpResponseMessage required = await _client.GetAsync(path);
        Assert.Equal(HttpStatusCode.Unauthorized, required.StatusCode);

        _client.DefaultRequestHeaders.Add("X-Api-Key", GlobalApiKeyValue);
        using HttpResponseMessage globalKey = await _client.GetAsync(path);
        Assert.Equal(HttpStatusCode.OK, globalKey.StatusCode);
        AssertNoSideEffects();
    }

    [Fact]
    public async Task OtherRoute_OptionalUploadsEnabled_RemainsProtectedByFallbackPolicy()
    {
        using HttpResponseMessage response = await _client.GetAsync("/protected");

        Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
        AssertNoSideEffects();
    }

    [Fact]
    public async Task Upload_AnonymousRateLimited_RejectsBeforeSaving()
    {
        _rateLimits.Setup(service => service.CheckOctoPrintUploadLimitAsync(
                It.IsAny<string>(), It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new RateLimitResult(false, 0));

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.TooManyRequests, response.StatusCode);
        AssertNoSideEffects();
    }

    [Fact]
    public async Task Upload_AnonymousWithoutCompatiblePrinter_ReturnsUploadedOnly()
    {
        _queue.Setup(service => service.AddJobToQueueAsync(
                It.IsAny<QueuePrintJobDto>(), null, It.IsAny<CancellationToken>()))
            .ReturnsAsync((JobQueuePrintJobDto?)null);

        using HttpResponseMessage response = await UploadAsync();

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        using JsonDocument body = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
        Assert.Equal("UploadedOnly", body.RootElement.GetProperty("status").GetString());
        Assert.Equal(_fileId.ToString(), body.RootElement.GetProperty("file").GetProperty("id").GetString());
        VerifyQueuedActor(null);
    }

    public async Task DisposeAsync()
    {
        _client?.Dispose();
        await _host.StopAsync();
        _host.Dispose();
    }

    private ApiKey SeedApiKey(bool rawKey = false)
    {
        var key = new ApiKey { UserId = _userId, Purpose = ApiKeyPurpose.OctoPrint, IsActive = true };
        if (rawKey)
        {
            _apiKeys.Setup(repository => repository.GetByRawKeyAsync(ApiKeyValue)).ReturnsAsync(key);
        }
        else
        {
            string hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(ApiKeyValue)));
            _apiKeys.Setup(repository => repository.GetByKeyHashAsync(hash)).ReturnsAsync(key);
        }

        return key;
    }

    private void SetBearer(string? subject, bool grantQueuePermission = true)
    {
        List<Claim> claims = [];
        if (subject is not null)
        {
            claims.Add(new Claim(ClaimTypes.NameIdentifier, subject));
        }

        if (grantQueuePermission)
        {
            claims.Add(new Claim(PrintFarmerPermissions.ClaimType, PrintFarmerPermissions.Queue.Write));
        }

        var token = new JwtSecurityToken(
            issuer: "PrintFarmer",
            audience: "PrintFarmer",
            claims: claims,
            expires: DateTime.UtcNow.AddMinutes(5),
            signingCredentials: new SigningCredentials(
                new SymmetricSecurityKey(Encoding.UTF8.GetBytes(SigningKey)), SecurityAlgorithms.HmacSha256));
        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
            "Bearer", new JwtSecurityTokenHandler().WriteToken(token));
    }

    private async Task<HttpResponseMessage> UploadAsync(bool print = true)
    {
        using var form = new MultipartFormDataContent();
        using var content = new ByteArrayContent(Encoding.UTF8.GetBytes(Gcode));
        content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
        form.Add(content, "file", "upload.gcode");
        form.Add(new StringContent(print ? "true" : "false"), "print");
        return await _client.PostAsync($"/api/files/local?printerId={_printerId}", form);
    }

    private void VerifyQueuedActor(Guid? actor)
    {
        _queue.Verify(service => service.AddJobToQueueAsync(
            It.Is<QueuePrintJobDto>(request =>
                request.GcodeFileId == _fileId &&
                request.AssignedPrinterId == _printerId &&
                request.RequiredPrinterModel == "Qidi Plus 4" &&
                request.RequiredNozzleDiameter == 0.4m &&
                request.RequiredMaterialType == "PLA"),
            actor,
            It.IsAny<CancellationToken>()), Times.Once);
    }

    private async Task AssertAuthenticationRejectedAsync(HttpResponseMessage response)
    {
        Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
        using JsonDocument body = JsonDocument.Parse(await response.Content.ReadAsStringAsync());
        Assert.Equal("authentication_required", body.RootElement.GetProperty("code").GetString());
        AssertNoSideEffects();
    }

    private void AssertNoSideEffects()
    {
        Assert.Empty(_files.Invocations);
        Assert.Empty(_queue.Invocations);
    }
}
