using System.Text.RegularExpressions;
using Farm.Infrastructure.Telemetry;

namespace Farm.Web.Api.Services.Gcode;

/// <summary>
/// Extracts metadata from G-code files as a fallback when printer API doesn't provide complete info.
/// Parses common comment patterns to extract slicer info, material, nozzle diameter, print time, filament length, etc.
/// </summary>
public interface IGcodeMetadataExtractorService
{
    /// <summary>
    /// Extract metadata from G-code content.
    /// </summary>
    Task<GcodeMetadataExtracted> ExtractMetadataAsync(string gcodeContent);
}

public class GcodeMetadataExtracted
{
    public string? SlicerName { get; set; }
    public string? SlicerVersion { get; set; }
    public double? EstimatedPrintTimeMinutes { get; set; }
    public double? FilamentLengthMm { get; set; }
    public double? FilamentWeightGrams { get; set; }
    public double? NozzleDiameter { get; set; }
    public string? Material { get; set; }
    public double? LayerHeight { get; set; }
    public byte[]? ThumbnailData { get; set; } // PNG image data extracted from gcode
}

public class GcodeMetadataExtractorService : IGcodeMetadataExtractorService
{
    private readonly IUnifiedLoggingService _logger;

    public GcodeMetadataExtractorService(IUnifiedLoggingService logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Extract metadata from G-code file content by parsing comment lines.
    /// Handles metadata from PrusaSlicer, Cura, OrcaSlicer, and generic patterns.
    /// </summary>
    public async Task<GcodeMetadataExtracted> ExtractMetadataAsync(string gcodeContent)
    {
        return await Task.Run(() =>
        {
            var metadata = new GcodeMetadataExtracted();

            if (string.IsNullOrWhiteSpace(gcodeContent))
            {
                return metadata;
            }

            try
            {
                var lines = gcodeContent.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);

                // Parse the first ~500 lines (metadata is typically at the start)
                var metadataLines = lines.Take(500).ToList();

                ExtractSlicerInfo(metadataLines, metadata);
                ExtractMaterial(metadataLines, metadata);
                ExtractNozzleDiameter(metadataLines, metadata);
                ExtractLayerHeight(metadataLines, metadata);
                ExtractPrintTime(metadataLines, metadata);
                ExtractFilamentInfo(metadataLines, metadata);
                ExtractThumbnail(metadataLines, metadata);

                return metadata;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Error extracting G-code metadata");
                return metadata;
            }
        });
    }

    private void ExtractSlicerInfo(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; generated by PrusaSlicer 2.5.0 on 2024-01-15 at 14:32:15 UTC"
        var slicerLine = lines.FirstOrDefault(l => l.Contains("generated by", StringComparison.OrdinalIgnoreCase));
        if (slicerLine != null)
        {
            // PrusaSlicer pattern: "; generated by PrusaSlicer X.Y.Z"
            var match = Regex.Match(slicerLine, @"(?:PrusaSlicer|OrcaSlicer|Cura|SuperSlicer)\s+([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                metadata.SlicerName = match.Groups[0].Value.Split()[0]; // Get first word (slicer name)
                metadata.SlicerVersion = match.Groups[1].Value;
            }
        }

        // Cura: "; Cura_Version:4.10.0"
        var curaLine = lines.FirstOrDefault(l => l.Contains("Cura_Version", StringComparison.OrdinalIgnoreCase));
        if (curaLine != null)
        {
            var match = Regex.Match(curaLine, @"Cura_Version:(.+)$", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                metadata.SlicerName = "Cura";
                metadata.SlicerVersion = match.Groups[1].Value.Trim();
            }
        }
    }

    private void ExtractMaterial(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; filament_type = PLA" or "; MATERIAL = PLA"
        var materialLine = lines.FirstOrDefault(l =>
            l.Contains("filament_type", StringComparison.OrdinalIgnoreCase) ||
            l.Contains("MATERIAL", StringComparison.OrdinalIgnoreCase) ||
            l.Contains("material:", StringComparison.OrdinalIgnoreCase));

        if (materialLine != null)
        {
            var match = Regex.Match(materialLine, @"(?:filament_type|MATERIAL|material)\s*[:=]\s*(.+)", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                var material = match.Groups[1].Value.Trim();
                metadata.Material = material.Trim(';', ' ', '"');
            }
        }
    }

    private void ExtractNozzleDiameter(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; nozzle_diameter = 0.4"
        var nozzleLine = lines.FirstOrDefault(l => l.Contains("nozzle_diameter", StringComparison.OrdinalIgnoreCase));
        if (nozzleLine != null)
        {
            var match = Regex.Match(nozzleLine, @"nozzle_diameter\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out var diameter))
            {
                metadata.NozzleDiameter = diameter;
            }
        }
    }

    private void ExtractLayerHeight(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; layer_height = 0.2"
        var layerLine = lines.FirstOrDefault(l => l.Contains("layer_height", StringComparison.OrdinalIgnoreCase));
        if (layerLine != null)
        {
            var match = Regex.Match(layerLine, @"layer_height\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out var height))
            {
                metadata.LayerHeight = height;
            }
        }
    }

    private void ExtractPrintTime(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // Multiple formats:
        // PrusaSlicer: "; estimated printing time (normal mode) = 1h 23m 45s"
        // Generic: "; TIME: 5025" (seconds)
        // Cura: "; Time: 123456" (seconds)

        var timeLine = lines.FirstOrDefault(l =>
            (l.Contains("estimated printing time", StringComparison.OrdinalIgnoreCase) ||
             l.Contains("TIME:", StringComparison.OrdinalIgnoreCase) ||
             l.Contains("; Time:", StringComparison.OrdinalIgnoreCase)) &&
            !l.Contains("remaining", StringComparison.OrdinalIgnoreCase));

        if (timeLine != null)
        {
            // Try PrusaSlicer format: "1h 23m 45s"
            var prusaMatch = Regex.Match(timeLine, @"(\d+)h\s+(\d+)m\s+(\d+)s");
            if (prusaMatch.Success)
            {
                var hours = int.Parse(prusaMatch.Groups[1].Value);
                var minutes = int.Parse(prusaMatch.Groups[2].Value);
                var seconds = int.Parse(prusaMatch.Groups[3].Value);
                metadata.EstimatedPrintTimeMinutes = hours * 60 + minutes + seconds / 60.0;
            }
            else
            {
                // Try seconds format: "TIME: 5025"
                var secondsMatch = Regex.Match(timeLine, @"(?:TIME|Time):\s*(\d+)", RegexOptions.IgnoreCase);
                if (secondsMatch.Success && int.TryParse(secondsMatch.Groups[1].Value, out var seconds))
                {
                    metadata.EstimatedPrintTimeMinutes = seconds / 60.0;
                }
            }
        }
    }

    private void ExtractFilamentInfo(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; filament_mm3 = 123.45" (mm³) or "; filament_length = 12345" (mm)
        // Cura: "; Filament used: 12.34m" or similar

        var filamentLengthLine = lines.FirstOrDefault(l => l.Contains("filament_length", StringComparison.OrdinalIgnoreCase));
        if (filamentLengthLine != null)
        {
            var match = Regex.Match(filamentLengthLine, @"filament_length\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out var length))
            {
                metadata.FilamentLengthMm = length;
            }
        }

        var filamentWeightLine = lines.FirstOrDefault(l =>
            (l.Contains("filament_g", StringComparison.OrdinalIgnoreCase) ||
             l.Contains("filament_weight", StringComparison.OrdinalIgnoreCase)) &&
            !l.Contains("mm3", StringComparison.OrdinalIgnoreCase));

        if (filamentWeightLine != null)
        {
            var match = Regex.Match(filamentWeightLine, @"(?:filament_g|filament_weight)\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out var weight))
            {
                metadata.FilamentWeightGrams = weight;
            }
        }
    }

    private void ExtractThumbnail(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer/OrcaSlicer format: `;thumbnail` comment blocks with base64-encoded PNG
        // Example:
        // ;thumbnail_QOI begin 200x200 Q0/10
        // ;iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAA...
        // ;thumbnail_QOI end
        //
        // Or alternative format:
        // ;thumbnail begin 200x200
        // ;base64 data...
        // ;thumbnail end

        try
        {
            var thumbnailLines = new List<string>();
            bool inThumbnail = false;

            foreach (var line in lines)
            {
                if (line.StartsWith(";thumbnail", StringComparison.OrdinalIgnoreCase))
                {
                    if (line.Contains("begin", StringComparison.OrdinalIgnoreCase))
                    {
                        inThumbnail = true;
                        continue;
                    }

                    if (line.Contains("end", StringComparison.OrdinalIgnoreCase))
                    {
                        if (inThumbnail)
                        {
                            break;
                        }
                    }
                }

                if (inThumbnail && line.StartsWith(';'))
                {
                    // Extract base64 data from comment line (remove leading ";")
                    var data = line.TrimStart(';').Trim();
                    if (!string.IsNullOrEmpty(data))
                    {
                        thumbnailLines.Add(data);
                    }
                }
            }

            if (thumbnailLines.Count > 0)
            {
                try
                {
                    string base64Data = string.Concat(thumbnailLines);
                    // Validate it's actual base64
                    if (base64Data.Length % 4 == 0 && IsValidBase64(base64Data))
                    {
                        metadata.ThumbnailData = Convert.FromBase64String(base64Data);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Failed to decode base64 thumbnail data from gcode");
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Error extracting thumbnail from G-code");
        }
    }

    private static bool IsValidBase64(string input)
    {
        // Base64 should only contain valid characters: A-Z, a-z, 0-9, +, /, =
        try
        {
            if (string.IsNullOrEmpty(input))
            {
                return false;
            }

            // Try to decode - this is the safest check
            _ = Convert.FromBase64String(input);
            return true;
        }
        catch
        {
            return false;
        }
    }
}
