using System.Text.RegularExpressions;
using Farm.Infrastructure.Telemetry;

namespace Farm.Infrastructure.Services.Gcode;

public class GcodeMetadataExtractorService(IUnifiedLoggingService logger) : IGcodeMetadataExtractorService
{
    private readonly IUnifiedLoggingService _logger = logger ?? throw new ArgumentNullException(nameof(logger));

    /// <summary>
    /// Extract metadata from G-code file content by parsing comment lines.
    /// Handles metadata from PrusaSlicer, Cura, OrcaSlicer, and generic patterns.
    /// </summary>
    public async Task<GcodeMetadataExtracted> ExtractMetadataAsync(string gcodeContent)
    {
        return await Task.Run(() =>
        {
            _logger.LogInformation("ExtractMetadataAsync: Starting metadata extraction");
            GcodeMetadataExtracted metadata = new();

            if (string.IsNullOrWhiteSpace(gcodeContent))
            {
                _logger.LogWarning("ExtractMetadataAsync: G-code content is empty or null");
                return metadata;
            }

            try
            {
                string[] allLines = gcodeContent.Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);

                // Include a wider range to capture all thumbnails:
                // - First 200 lines: basic slicer info and comments
                // - Last 2000 lines: config block with all thumbnails (PrusaSlicer embeds multiple)
                // This ensures we capture all thumbnail formats (QOI + PNG) which can appear deep in the file
                List<string> metadataLines = new List<string>();

                // Add first 200 lines
                int firstLinesCount = Math.Min(200, allLines.Length);
                metadataLines.AddRange(allLines.Take(firstLinesCount));
                _logger.LogInformation("ExtractMetadataAsync: Added {Count} lines from start", firstLinesCount.ToString());

                // Add last 2000 lines (increased from 1000 to capture all PrusaSlicer thumbnails)
                // PrusaSlicer embeds 3 QOI thumbnails + 1 PNG thumbnail, and PNG can start at line ~1300
                if (allLines.Length > 2000)
                {
                    int startIndex = allLines.Length - 2000;
                    metadataLines.AddRange(allLines.Skip(startIndex).Take(2000));
                    _logger.LogInformation("ExtractMetadataAsync: Added 2000 lines from end (starting at line {StartLine})", startIndex.ToString());
                }

                _logger.LogInformation("ExtractMetadataAsync: Processing {LineCount} lines total from {TotalLines} total", metadataLines.Count.ToString(), allLines.Length.ToString());

                // Extract all metadata from the combined set
                ExtractSlicerInfo(metadataLines, metadata);
                ExtractMaterial(metadataLines, metadata);
                ExtractNozzleDiameter(metadataLines, metadata);
                ExtractLayerHeight(metadataLines, metadata);
                ExtractPrintTime(metadataLines, metadata);
                ExtractFilamentInfo(metadataLines, metadata);
                ExtractTemperatures(metadataLines, metadata);
                ExtractPrinterModel(metadataLines, metadata);
                ExtractPrintSettingsId(metadataLines, metadata);
                ExtractInfill(metadataLines, metadata);
                ExtractPerimeters(metadataLines, metadata);
                _logger.LogInformation("ExtractMetadataAsync: About to extract thumbnail");
                ExtractThumbnail(allLines, metadata);
                _logger.LogInformation("ExtractMetadataAsync: Thumbnail extraction complete, ThumbnailData={HasData}", metadata.ThumbnailData != null ? $"{metadata.ThumbnailData.Length} bytes" : "null");

                _logger.LogInformation($"ExtractMetadataAsync: Extracted metadata - Slicer={metadata.SlicerName ?? "(unknown)"} {metadata.SlicerVersion ?? string.Empty}, Material={metadata.Material ?? "(unknown)"}, NozzleDiameter={metadata.NozzleDiameter?.ToString("F1") ?? "0"}, PrintTime={metadata.EstimatedPrintTimeMinutes?.ToString("F0") ?? "0"}min, Filament={metadata.FilamentWeightGrams?.ToString("F1") ?? "0"}g, LayerHeight={metadata.LayerHeight?.ToString("F2") ?? "0"}, BedTemp={metadata.BedTemperature?.ToString("F0") ?? "0"}°C, PrintTemp={metadata.PrintTemperature?.ToString("F0") ?? "0"}°C");

                return metadata;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Error extracting G-code metadata");
                return metadata;
            }
        });
    }

    private void ExtractSlicerInfo(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; generated by PrusaSlicer 2.5.0 on 2024-01-15 at 14:32:15 UTC"
        string? slicerLine = lines.FirstOrDefault(l => l.Contains("generated by", StringComparison.OrdinalIgnoreCase));
        if (slicerLine != null)
        {
            // PrusaSlicer pattern: "; generated by PrusaSlicer X.Y.Z"
            Match match = Regex.Match(slicerLine, @"(?:PrusaSlicer|OrcaSlicer|Cura|SuperSlicer)\s+([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                metadata.SlicerName = match.Groups[0].Value.Split()[0]; // Get first word (slicer name)
                metadata.SlicerVersion = match.Groups[1].Value;
                _logger.LogInformation("ExtractSlicerInfo: Found {SlicerName} {Version}", metadata.SlicerName, metadata.SlicerVersion);
            }
        }

        // Cura: "; Cura_Version:4.10.0"
        string? curaLine = lines.FirstOrDefault(l => l.Contains("Cura_Version", StringComparison.OrdinalIgnoreCase));
        if (curaLine != null)
        {
            Match match = Regex.Match(curaLine, @"Cura_Version:(.+)$", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                metadata.SlicerName = "Cura";
                metadata.SlicerVersion = match.Groups[1].Value.Trim();
                _logger.LogInformation("ExtractSlicerInfo: Found Cura {Version}", metadata.SlicerVersion);
            }
        }
    }

    private void ExtractMaterial(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; filament_type = PLA" or "; MATERIAL = PLA"
        // Explicitly match comment syntax to avoid matching in other contexts
        foreach (string line in lines)
        {
            Match match = Regex.Match(line, @";\s*(?:filament_type|MATERIAL|material)\s*[:=]\s*([^;]+)", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                string material = match.Groups[1].Value.Trim();
                metadata.Material = material.Trim(';', ' ', '"');
                _logger.LogInformation("ExtractMaterial: Found {Material}", metadata.Material);
                break; // Take first match
            }
        }
    }

    private void ExtractNozzleDiameter(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; nozzle_diameter = 0.4"
        // OrcaSlicer: "; nozzle_diameter = 0.6"
        // Explicitly match comment syntax
        foreach (string line in lines)
        {
            Match match = Regex.Match(line, @";\s*nozzle_diameter\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out double diameter))
            {
                metadata.NozzleDiameter = diameter;
                _logger.LogInformation("ExtractNozzleDiameter: Found {Diameter}mm", diameter.ToString("F1"));
                break; // Take first match
            }
        }
    }

    private void ExtractLayerHeight(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; layer_height = 0.2"
        // OrcaSlicer: "; layer_height = 0.2"
        // Explicitly match comment syntax to avoid matching other properties like first_layer_height
        foreach (string line in lines)
        {
            Match match = Regex.Match(line, @";\s*layer_height\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out double height))
            {
                metadata.LayerHeight = height;
                _logger.LogInformation("ExtractLayerHeight: Found {Height}mm", height.ToString("F2"));
                break; // Take first match
            }
        }
    }

    private void ExtractPrintTime(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // Multiple formats:
        // PrusaSlicer/OrcaSlicer: "; estimated printing time (normal mode) = 1h 23m 45s" or "26m 5s"
        // Generic: "; TIME: 5025" (seconds)
        // Cura: "; Time: 123456" (seconds)
        // Priority: normal mode > generic/TIME > other modes

        // First pass: Look specifically for "normal mode"
        foreach (string line in lines)
        {
            if (line.Contains("estimated printing time (normal mode)", StringComparison.OrdinalIgnoreCase))
            {
                // Try hours format: "1h 23m 45s"
                Match hoursMatch = Regex.Match(line, @"(\d+)h\s+(\d+)m\s+(\d+)s");
                if (hoursMatch.Success)
                {
                    int hours = int.Parse(hoursMatch.Groups[1].Value);
                    int minutes = int.Parse(hoursMatch.Groups[2].Value);
                    int seconds = int.Parse(hoursMatch.Groups[3].Value);
                    metadata.EstimatedPrintTimeMinutes = (hours * 60) + minutes + (seconds / 60.0);
                    _logger.LogInformation("ExtractPrintTime: Found {Minutes}min (normal mode)", (metadata.EstimatedPrintTimeMinutes ?? 0).ToString("F0"));
                    return;
                }

                // Try minutes-only format: "26m 5s"
                Match minMatch = Regex.Match(line, @"(\d+)m\s+(\d+)s");
                if (minMatch.Success)
                {
                    int minutes = int.Parse(minMatch.Groups[1].Value);
                    int seconds = int.Parse(minMatch.Groups[2].Value);
                    metadata.EstimatedPrintTimeMinutes = minutes + (seconds / 60.0);
                    _logger.LogInformation("ExtractPrintTime: Found {Minutes}min (normal mode)", (metadata.EstimatedPrintTimeMinutes ?? 0).ToString("F0"));
                    return;
                }
            }
        }

        // Second pass: Try generic TIME formats
        foreach (string line in lines)
        {
            if (line.Contains("TIME:", StringComparison.OrdinalIgnoreCase) ||
                line.Contains("; Time:", StringComparison.OrdinalIgnoreCase))
            {
                Match secondsMatch = Regex.Match(line, @"(?:TIME|Time):\s*(\d+)", RegexOptions.IgnoreCase);
                if (secondsMatch.Success && int.TryParse(secondsMatch.Groups[1].Value, out int seconds))
                {
                    metadata.EstimatedPrintTimeMinutes = seconds / 60.0;
                    _logger.LogInformation("ExtractPrintTime: Found {Minutes}min (TIME format)", (metadata.EstimatedPrintTimeMinutes ?? 0).ToString("F0"));
                    return;
                }
            }
        }

        // Third pass: Fall back to any "estimated printing time" (excluding remaining/first layer)
        foreach (string line in lines)
        {
            if (line.Contains("remaining", StringComparison.OrdinalIgnoreCase) ||
                line.Contains("first layer", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            if (line.Contains("estimated printing time", StringComparison.OrdinalIgnoreCase))
            {
                // Try hours format
                Match hoursMatch = Regex.Match(line, @"(\d+)h\s+(\d+)m\s+(\d+)s");
                if (hoursMatch.Success)
                {
                    int hours = int.Parse(hoursMatch.Groups[1].Value);
                    int minutes = int.Parse(hoursMatch.Groups[2].Value);
                    int seconds = int.Parse(hoursMatch.Groups[3].Value);
                    metadata.EstimatedPrintTimeMinutes = (hours * 60) + minutes + (seconds / 60.0);
                    _logger.LogInformation("ExtractPrintTime: Found {Minutes}min", (metadata.EstimatedPrintTimeMinutes ?? 0).ToString("F0"));
                    return;
                }

                // Try minutes-only format
                Match minMatch = Regex.Match(line, @"(\d+)m\s+(\d+)s");
                if (minMatch.Success)
                {
                    int minutes = int.Parse(minMatch.Groups[1].Value);
                    int seconds = int.Parse(minMatch.Groups[2].Value);
                    metadata.EstimatedPrintTimeMinutes = minutes + (seconds / 60.0);
                    _logger.LogInformation("ExtractPrintTime: Found {Minutes}min", (metadata.EstimatedPrintTimeMinutes ?? 0).ToString("F0"));
                    return;
                }
            }
        }
    }

    private void ExtractFilamentInfo(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; filament_mm3 = 123.45" (mm³) or "; filament_length = 12345" (mm)
        // Cura: "; Filament used: 12.34m" or similar
        // CONFIG_BLOCK: "; filament used [mm] = 3538.91" and "; filament used [g] = 10.55"

        // Try standard format first - explicit comment syntax
        string? filamentLengthLine = lines.FirstOrDefault(l => l.Contains("filament_length", StringComparison.OrdinalIgnoreCase));
        if (filamentLengthLine != null)
        {
            Match match = Regex.Match(filamentLengthLine, @";\s*filament_length\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out double length))
            {
                metadata.FilamentLengthMm = length;
                _logger.LogInformation("ExtractFilamentInfo: Found {Length}mm of filament", length.ToString("F0"));
            }
        }

        // Also try CONFIG_BLOCK format: "; filament used [mm] = 3538.91" - explicit comment syntax
        if (metadata.FilamentLengthMm == null)
        {
            string? configFilamentLengthLine = lines.FirstOrDefault(l => l.Contains("filament used [mm]", StringComparison.OrdinalIgnoreCase));
            if (configFilamentLengthLine != null)
            {
                Match match = Regex.Match(configFilamentLengthLine, @";\s*filament used \[mm\]\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
                if (match.Success && double.TryParse(match.Groups[1].Value, out double length))
                {
                    metadata.FilamentLengthMm = length;
                    _logger.LogInformation("ExtractFilamentInfo: Found {Length}mm of filament from CONFIG_BLOCK", length.ToString("F0"));
                }
            }
        }

        // Try standard format first - explicit comment syntax
        string? filamentWeightLine = lines.FirstOrDefault(l =>
            (l.Contains("filament_g", StringComparison.OrdinalIgnoreCase) ||
             l.Contains("filament_weight", StringComparison.OrdinalIgnoreCase)) &&
            !l.Contains("mm3", StringComparison.OrdinalIgnoreCase) &&
            !l.Contains("[", StringComparison.OrdinalIgnoreCase));

        if (filamentWeightLine != null)
        {
            Match match = Regex.Match(filamentWeightLine, @";\s*(?:filament_g|filament_weight)\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out double weight))
            {
                metadata.FilamentWeightGrams = weight;
                _logger.LogInformation("ExtractFilamentInfo: Found {Weight}g of filament", weight.ToString("F1"));
            }
        }

        // Also try CONFIG_BLOCK format: "; filament used [g] = 10.55" - explicit comment syntax
        if (metadata.FilamentWeightGrams == null)
        {
            string? configFilamentWeightLine = lines.FirstOrDefault(l => l.Contains("filament used [g]", StringComparison.OrdinalIgnoreCase));
            if (configFilamentWeightLine != null)
            {
                Match match = Regex.Match(configFilamentWeightLine, @";\s*filament used \[g\]\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
                if (match.Success && double.TryParse(match.Groups[1].Value, out double weight))
                {
                    metadata.FilamentWeightGrams = weight;
                    _logger.LogInformation("ExtractFilamentInfo: Found {Weight}g of filament from CONFIG_BLOCK", weight.ToString("F1"));
                }
            }
        }
    }

    private void ExtractTemperatures(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // Extract first layer temperatures
        // OrcaSlicer: "; first_layer_bed_temperature = 55" and "; first_layer_temperature = 220"
        // PrusaSlicer: "; first_layer_bed_temperature = 110" and "; first_layer_temperature = 260"
        // Explicitly match comment syntax
        foreach (string line in lines)
        {
            // Bed temperature - explicit comment syntax
            Match bedMatch = Regex.Match(line, @";\s*first_layer_bed_temperature\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (bedMatch.Success && double.TryParse(bedMatch.Groups[1].Value, out double bedTemp))
            {
                metadata.BedTemperature = bedTemp;
                _logger.LogInformation("ExtractTemperatures: Found bed temperature {Temp}°C", bedTemp.ToString("F0"));
            }

            // Nozzle/hotend temperature - explicit comment syntax
            Match nozzleMatch = Regex.Match(line, @";\s*first_layer_temperature\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (nozzleMatch.Success && double.TryParse(nozzleMatch.Groups[1].Value, out double nozzleTemp))
            {
                metadata.PrintTemperature = nozzleTemp;
                _logger.LogInformation("ExtractTemperatures: Found nozzle temperature {Temp}°C", nozzleTemp.ToString("F0"));
            }
        }
    }

    private void ExtractThumbnail(string[] allLines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer/OrcaSlicer format: `;thumbnail` comment blocks with base64-encoded image data
        //
        // PrusaSlicer embeds multiple thumbnails at different sizes in this order:
        // 1. Three QOI-format thumbnails (thumbnail_QOI begin/end blocks) at different resolutions
        // 2. Multiple PNG-format thumbnails (thumbnail begin/end block) at various resolutions
        //
        // OrcaSlicer embeds QOI format thumbnails early in the file
        //
        // Examples:
        // ;thumbnail_QOI begin 200x200 Q0/10
        // ;iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAA...
        // ;thumbnail_QOI end
        //
        // ;thumbnail begin 380x285
        // ;base64 PNG data...
        // ;thumbnail end
        //
        // We select the LARGEST PNG thumbnail for best quality previews.
        try
        {
            _logger.LogInformation("ExtractThumbnail: Starting thumbnail extraction from {LineCount} lines", allLines.Length.ToString());

            // Convert to list for easier processing
            var lines = new List<string>(allLines);

            // Store all found thumbnails with their format, dimensions, and data
            List<(string Format, int Width, int Height, List<string> Data)> thumbnailBlocks = new();
            List<string> currentThumbnailLines = new List<string>();
            string? currentThumbnailFormat = null;
            int currentWidth = 0;
            int currentHeight = 0;
            bool inThumbnail = false;

            foreach (string line in lines)
            {
                // Check if line contains thumbnail marker (handle both ";thumbnail" and "; thumbnail" formats)
                if (line.StartsWith(';'))
                {
                    string trimmedAfterSemicolon = line.Substring(1).TrimStart();
                    if (trimmedAfterSemicolon.StartsWith("thumbnail", StringComparison.OrdinalIgnoreCase))
                    {
                        _logger.LogDebug("ExtractThumbnail: Found thumbnail line: {Line}", line.Substring(0, Math.Min(80, line.Length)));

                        if (line.Contains("begin", StringComparison.OrdinalIgnoreCase))
                        {
                            // Detect format: QOI or PNG
                            currentThumbnailFormat = line.Contains("_QOI", StringComparison.OrdinalIgnoreCase) ? "QOI" : "PNG";

                            // Parse dimensions from line like ";thumbnail begin 380x285" or ";thumbnail_QOI begin 200x200 Q0/10"
                            currentWidth = 0;
                            currentHeight = 0;
                            Match dimensionMatch = Regex.Match(line, @"(\d+)x(\d+)", RegexOptions.IgnoreCase);
                            if (dimensionMatch.Success)
                            {
                                _ = int.TryParse(dimensionMatch.Groups[1].Value, out currentWidth);
                                _ = int.TryParse(dimensionMatch.Groups[2].Value, out currentHeight);
                            }

                            inThumbnail = true;
                            currentThumbnailLines = new List<string>();
                            _logger.LogDebug($"ExtractThumbnail: {currentThumbnailFormat} thumbnail block started ({currentWidth}x{currentHeight})");
                            continue;
                        }

                        if (line.Contains("end", StringComparison.OrdinalIgnoreCase))
                        {
                            if (inThumbnail)
                            {
                                // Store this thumbnail block with all its metadata
                                thumbnailBlocks.Add((currentThumbnailFormat!, currentWidth, currentHeight, new List<string>(currentThumbnailLines)));
                                _logger.LogDebug($"ExtractThumbnail: {currentThumbnailFormat} thumbnail block ended ({currentWidth}x{currentHeight}), collected {currentThumbnailLines.Count} lines");
                                inThumbnail = false;
                                currentThumbnailFormat = null;
                                currentWidth = 0;
                                currentHeight = 0;
                            }
                        }
                    }
                }

                if (inThumbnail && line.StartsWith(';'))
                {
                    // Extract base64/data from comment line (remove leading ";")
                    string data = line.TrimStart(';').Trim();
                    if (!string.IsNullOrEmpty(data) && !data.StartsWith("thumbnail", StringComparison.OrdinalIgnoreCase) && !data.StartsWith("THUMBNAIL", StringComparison.OrdinalIgnoreCase))
                    {
                        currentThumbnailLines.Add(data);
                    }
                }
            }

            _logger.LogInformation("ExtractThumbnail: Found {Count} thumbnail blocks total", thumbnailBlocks.Count.ToString());

            // Select the LARGEST PNG thumbnail (by pixel count = width * height)
            // If no PNG found, fall back to largest QOI
            (string? Format, int Width, int Height, List<string>? Lines) selectedThumbnail = default;

            // Get all PNG thumbnails and select the largest
            var pngThumbnails = thumbnailBlocks.Where(t => t.Format == "PNG").ToList();
            if (pngThumbnails.Count > 0)
            {
                var largest = pngThumbnails.OrderByDescending(t => t.Width * t.Height).First();
                selectedThumbnail = largest;
                _logger.LogInformation($"ExtractThumbnail: Selected largest PNG thumbnail ({largest.Width}x{largest.Height}) from {pngThumbnails.Count} PNG options");
            }
            else
            {
                // Fall back to largest QOI if no PNG available
                var qoiThumbnails = thumbnailBlocks.Where(t => t.Format == "QOI").ToList();
                if (qoiThumbnails.Count > 0)
                {
                    var largest = qoiThumbnails.OrderByDescending(t => t.Width * t.Height).First();
                    selectedThumbnail = largest;
                    _logger.LogInformation($"ExtractThumbnail: Selected largest QOI thumbnail ({largest.Width}x{largest.Height}) from {qoiThumbnails.Count} QOI options (no PNG found)");
                }
                else if (thumbnailBlocks.Count > 0)
                {
                    // Fallback: use largest available thumbnail of any format
                    var largest = thumbnailBlocks.OrderByDescending(t => t.Width * t.Height).First();
                    selectedThumbnail = largest;
                    _logger.LogInformation($"ExtractThumbnail: Selected largest {largest.Format} thumbnail ({largest.Width}x{largest.Height}) as fallback");
                }
            }

            if (selectedThumbnail.Lines != null && selectedThumbnail.Lines.Count > 0)
            {
                string base64Data = string.Concat(selectedThumbnail.Lines);
                _logger.LogInformation($"ExtractThumbnail: Attempting to decode {selectedThumbnail.Format ?? "Unknown"} thumbnail ({selectedThumbnail.Width}x{selectedThumbnail.Height}) with {base64Data.Length} base64 chars");

                // Log first and last lines for debugging
                if (selectedThumbnail.Lines.Count > 0)
                {
                    _logger.LogDebug("ExtractThumbnail: First base64 line (len={Len}): {Data}", selectedThumbnail.Lines[0].Length.ToString(), selectedThumbnail.Lines[0].Substring(0, Math.Min(50, selectedThumbnail.Lines[0].Length)));
                    if (selectedThumbnail.Lines.Count > 1)
                    {
                        _logger.LogDebug("ExtractThumbnail: Last base64 line (len={Len}): {Data}", selectedThumbnail.Lines[selectedThumbnail.Lines.Count - 1].Length.ToString(), selectedThumbnail.Lines[selectedThumbnail.Lines.Count - 1].Substring(0, Math.Min(50, selectedThumbnail.Lines[selectedThumbnail.Lines.Count - 1].Length)));
                    }
                }

                try
                {
                    // Pad base64 data to valid length if needed
                    int paddingNeeded = (4 - (base64Data.Length % 4)) % 4;
                    if (paddingNeeded > 0)
                    {
                        base64Data = base64Data + new string('=', paddingNeeded);
                    }

                    // Validate it's actual base64
                    if (IsValidBase64(base64Data))
                    {
                        metadata.ThumbnailData = Convert.FromBase64String(base64Data);
                        _logger.LogInformation($"ExtractThumbnail: Successfully decoded {metadata.ThumbnailData.Length} bytes of {selectedThumbnail.Format ?? "Unknown"} thumbnail data ({selectedThumbnail.Width}x{selectedThumbnail.Height})");
                    }
                    else
                    {
                        _logger.LogWarning("ExtractThumbnail: Base64 data validation failed (length={Length}, could not decode)", base64Data.Length.ToString());
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Failed to decode base64 thumbnail data from gcode");
                }
            }
            else
            {
                _logger.LogWarning("ExtractThumbnail: No thumbnail data lines found in GCODE");
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Error extracting thumbnail from G-code");
        }
    }

    private static bool IsValidBase64(string input)
    {
        // Base64 should only contain valid characters: A-Z, a-z, 0-9, +, /, =
        try
        {
            if (string.IsNullOrEmpty(input))
            {
                return false;
            }

            // Try to decode - this is the safest check
            _ = Convert.FromBase64String(input);
            return true;
        }
        catch
        {
            return false;
        }
    }

    private void ExtractPrinterModel(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // OrcaSlicer: "; printer_model = Phrozen Arco"
        // Cura: "; machine_name = Prusa CORE One"
        // PrusaSlicer: "; printer_model = COREONEL"
        // Note: Avoid matching patterns like "printer_model=~/(COREONEL|.../ " which are conditions
        foreach (string line in lines)
        {
            // Match comment syntax: ; followed by optional whitespace, then the field name
            // Only match if the value after = doesn't start with ~/ (regex pattern)
            Match match = Regex.Match(line, @";\s*printer_model\s*[:=]\s*(?!~\/)([^;]+)", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                string model = match.Groups[1].Value.Trim();
                metadata.PrinterModel = model.Trim(';', ' ', '"');
                _logger.LogInformation("ExtractPrinterModel: Found {Model}", metadata.PrinterModel);
                break;
            }
        }
    }

    private void ExtractPrintSettingsId(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // OrcaSlicer: "; print_settings_id = Standard"
        // This identifies which slicer Process profile was used
        foreach (string line in lines)
        {
            Match match = Regex.Match(line, @"print_settings_id\s*[:=]\s*(.+)$", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                string settingsId = match.Groups[1].Value.Trim();
                metadata.PrintSettingsId = settingsId.Trim(';', ' ', '"');
                _logger.LogInformation("ExtractPrintSettingsId: Found {SettingsId}", metadata.PrintSettingsId);
                break;
            }
        }
    }

    private void ExtractInfill(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; fill_density = 15"
        // OrcaSlicer: "; sparse_infill_density = 15%" (represents the main infill, not skeleton or skin)
        foreach (string line in lines)
        {
            // First try to match sparse_infill_density (OrcaSlicer's main infill)
            Match match = Regex.Match(line, @";\s*sparse_infill_density\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out double infill))
            {
                metadata.InfillPercentage = infill;
                _logger.LogInformation("ExtractInfill: Found sparse_infill_density {Infill}%", infill.ToString("F1"));
                break;
            }

            // Fall back to fill_density (PrusaSlicer)
            match = Regex.Match(line, @"^(?!.*(?:skeleton|skin)).*fill_density\s*[:=]\s*([\d.]+)", RegexOptions.IgnoreCase);
            if (match.Success && double.TryParse(match.Groups[1].Value, out infill))
            {
                metadata.InfillPercentage = infill;
                _logger.LogInformation("ExtractInfill: Found fill_density {Infill}%", infill.ToString("F1"));
                break;
            }
        }
    }

    private void ExtractPerimeters(List<string> lines, GcodeMetadataExtracted metadata)
    {
        // PrusaSlicer: "; perimeters = 2"
        // OrcaSlicer: "; wall_loops = 2"
        // CRITICAL: Must avoid matching compound names like "avoid_crossing_perimeters"!
        _logger.LogInformation($"ExtractPerimeters: Searching through {lines.Count} lines for perimeters/wall_loops");

        foreach (string line in lines)
        {
            // Try wall_loops first (unambiguous)
            Match match = Regex.Match(line, @";\s*wall_loops\s*[:=]\s*(\d+)", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                _logger.LogInformation($"ExtractPerimeters: Matched wall_loops - Group[1]='{match.Groups[1].Value}'");

                if (int.TryParse(match.Groups[1].Value, out int wallLoops))
                {
                    metadata.Perimeters = wallLoops;
                    _logger.LogInformation($"ExtractPerimeters: Parsed wall_loops='{wallLoops}'. metadata.Perimeters={metadata.Perimeters}");
                    break;
                }
            }

            // For perimeters: Use negative lookbehind (?<!...) to ensure NOT preceded by letter or underscore
            // This prevents matching within compound words like "avoid_crossing_perimeters"
            match = Regex.Match(line, @";\s*perimeters\s*[:=]\s*(\d+)", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                _logger.LogInformation($"ExtractPerimeters: Matched perimeters - Group[1]='{match.Groups[1].Value}'");

                if (int.TryParse(match.Groups[1].Value, out int perimeters))
                {
                    metadata.Perimeters = perimeters;
                    _logger.LogInformation($"ExtractPerimeters: Parsed perimeters='{perimeters}'. metadata.Perimeters={metadata.Perimeters}");
                    break;
                }
            }
        }

        if (metadata.Perimeters == null)
        {
            _logger.LogInformation($"ExtractPerimeters: No perimeters/wall_loops found in {lines.Count} lines");
        }
    }
}
