// <auto-generated>
//     This code was generated by a tool.
//     Proto file: slicer_jobs.proto
//     This file is auto-generated by protoc. Do not edit by hand.
// </auto-generated>

#pragma warning disable CS0618, CS1591
namespace Farm.Web.Api.Grpc
{
    // Enumerations
    public enum JobStatus
    {
        Unknown = 0,
        Queued = 1,
        Slicing = 2,
        Completed = 3,
        Error = 4,
        Cancelled = 5,
    }

    public enum JobPriority
    {
        Unknown = 0,
        Low = 1,
        Normal = 2,
        High = 3,
        Critical = 4,
    }

    public enum SlicerEngineType
    {
        Unknown = 0,
        Orca = 1,
        Prusa = 2,
        Super = 3,
        Cura = 4,
    }

    public enum WorkerStatus
    {
        Unknown = 0,
        Idle = 1,
        Busy = 2,
        Offline = 3,
        Maintenance = 4,
        Error = 5,
    }
}
